export type PracticeItem = {
  id: number
  category: string
  title: string
  latex: string
  note: string
  meaning?: string
}

function makeCategory(category: string, items: Omit<PracticeItem, 'category'>[]) {
  return items.map((item) => ({ ...item, category }))
}

const algebra = makeCategory('대수', [
  { id: 1, title: '기본 분수', latex: String.raw`\frac{a+b}{c+d}`, note: '분수 기본기' },
  { id: 2, title: '인수분해 꼴', latex: String.raw`\frac{x^2-1}{x+1}`, note: '인수분해가 떠오르는 꼴' },
  { id: 3, title: '연분수', latex: String.raw`1+\frac{1}{1+\frac{1}{x}}`, note: '중첩 분수' },
  { id: 4, title: '이항식 1', latex: String.raw`(x+y)^2=x^2+2xy+y^2`, note: '전개식' },
  { id: 5, title: '이항식 2', latex: String.raw`(a-b)^2=a^2-2ab+b^2`, note: '전개식' },
  { id: 6, title: '지수 규칙', latex: String.raw`x^m x^n=x^{m+n}`, note: '지수 법칙' },
  { id: 7, title: '지수 분수', latex: String.raw`x^{\frac{1}{2}}=\sqrt{x}`, note: '루트와 지수' },
  { id: 8, title: '로그 법칙 1', latex: String.raw`\log(ab)=\log a+\log b`, note: '곱의 로그' },
  { id: 9, title: '로그 법칙 2', latex: String.raw`\log\frac{a}{b}=\log a-\log b`, note: '나눗셈 로그' },
  { id: 10, title: '대수 방정식', latex: String.raw`x^2-5x+6=0`, note: '이차방정식' },
  { id: 11, title: '완전제곱', latex: String.raw`x^2+2xy+y^2=(x+y)^2`, note: '완전제곱식' },
  { id: 12, title: '절댓값 방정식', latex: String.raw`|x-3|=2`, note: '절댓값' },
  { id: 13, title: '유리식', latex: String.raw`\frac{x^2-4}{x-2}=x+2`, note: '약분 꼴' },
  { id: 14, title: '근호 제거', latex: String.raw`\sqrt{x+1}=x-1`, note: '근호 포함 방정식' },
  { id: 15, title: '다항식', latex: String.raw`p(x)=x^4-3x^2+2`, note: '다항식' },
  { id: 16, title: '합성식', latex: String.raw`f(g(x))=x^2+1`, note: '합성 함수' },
  { id: 17, title: '조합식 1', latex: String.raw`\binom{n}{r}=\frac{n!}{r!(n-r)!}`, note: '조합 공식' },
  { id: 18, title: '조합식 2', latex: String.raw`{}_nC_r=\frac{n!}{r!(n-r)!}`, note: '표기 변형' },
  { id: 19, title: '순열', latex: String.raw`{}_nP_r=\frac{n!}{(n-r)!}`, note: '순열 공식' },
  { id: 20, title: '계승', latex: String.raw`n!=1\cdot2\cdot\cdots\cdot n`, note: '팩토리얼' },
  { id: 21, title: '부분분수', latex: String.raw`\frac{1}{x(x+1)}=\frac{1}{x}-\frac{1}{x+1}`, note: '부분분수 분해' },
  { id: 22, title: '대칭식', latex: String.raw`x+y=y+x`, note: '교환법칙' },
  { id: 23, title: '결합법칙', latex: String.raw`(x+y)+z=x+(y+z)`, note: '결합법칙' },
  { id: 24, title: '분배법칙', latex: String.raw`a(b+c)=ab+ac`, note: '분배법칙' },
  { id: 25, title: '거듭제곱', latex: String.raw`(x^m)^n=x^{mn}`, note: '거듭제곱 법칙' },
  { id: 26, title: '삼각함수 덧셈', latex: String.raw`\sin(x+y)=\sin x\cos y+\cos x\sin y`, note: '덧셈정리' },
  { id: 27, title: '삼각함수 덧셈2', latex: String.raw`\cos(x+y)=\cos x\cos y-\sin x\sin y`, note: '덧셈정리' },
  { id: 28, title: '이차식', latex: String.raw`ax^2+bx+c`, note: '기본 이차식' },
  { id: 29, title: '유리화', latex: String.raw`\frac{1}{\sqrt{2}}=\frac{\sqrt{2}}{2}`, note: '유리화' },
  { id: 30, title: '대입', latex: String.raw`x=2\Rightarrow x^2=4`, note: '대입' },
  { id: 31, title: '연립 1', latex: String.raw`\begin{cases} x+y=3\\ x-y=1 \end{cases}`, note: '연립방정식' },
  { id: 32, title: '연립 2', latex: String.raw`\begin{cases} 2x+3y=7\\ x-y=1 \end{cases}`, note: '연립방정식' },
  { id: 33, title: '분수식', latex: String.raw`\frac{x}{y}+\frac{y}{x}`, note: '분수 합' },
  { id: 34, title: '항등식', latex: String.raw`(x-1)(x+1)=x^2-1`, note: '항등식' },
  { id: 35, title: '다중 첨자', latex: String.raw`a_{m,n}^{k}`, note: '다중 첨자' },
  { id: 36, title: '절댓값2', latex: String.raw`|x|+|y|`, note: '절댓값 합' },
  { id: 37, title: '루트합', latex: String.raw`\sqrt{x}+\sqrt{y}`, note: '루트 합' },
  { id: 38, title: '로그 밑변환', latex: String.raw`\log_a b=\frac{\ln b}{\ln a}`, note: '밑변환' },
  { id: 39, title: '복소대수', latex: String.raw`(a+bi)(c+di)`, note: '복소수 곱' },
  { id: 40, title: '대수 종합', latex: String.raw`\frac{x^2-1}{x-1}=x+1`, note: '종합' },
  { id: 41, title: '치환 1', latex: String.raw`u=x^2+1`, note: '변수 치환' },
  { id: 42, title: '치환 2', latex: String.raw`v=\sqrt{x+1}`, note: '변수 치환' },
  { id: 43, title: '항등 2', latex: String.raw`(x+y)^3=x^3+3x^2y+3xy^2+y^3`, note: '전개' },
  { id: 44, title: '인수분해2', latex: String.raw`x^3-y^3=(x-y)(x^2+xy+y^2)`, note: '인수분해' },
  { id: 45, title: '삼차식', latex: String.raw`x^3+ax^2+bx+c`, note: '삼차식' },
  { id: 46, title: '라디칼', latex: String.raw`\sqrt[4]{x^4+y^4}`, note: '4제곱근' },
  { id: 47, title: '분모통일', latex: String.raw`\frac{a}{b}+\frac{c}{d}=\frac{ad+bc}{bd}`, note: '분모 통일' },
  { id: 48, title: '차수', latex: String.raw`\deg p(x)=n`, note: '차수' },
  { id: 49, title: '나눗셈', latex: String.raw`x=yq+r`, note: '나눗셈 정리' },
  { id: 50, title: '대수 마무리', latex: String.raw`\frac{1}{1-x}=\sum_{n=0}^{\infty} x^n`, note: '급수 연결' },
])

const calculus = makeCategory('미적분', [
  { id: 101, title: '정적분 1', latex: String.raw`\int_{0}^{1} x^2 \, dx`, note: '기본 정적분', meaning: '0부터 1까지 x² 아래 넓이를 구하는 정적분이야.' },
  { id: 102, title: '정적분 2', latex: String.raw`\int_{-\pi}^{\pi} \cos x \, dx`, note: '대칭 구간' },
  { id: 103, title: '부정적분', latex: String.raw`\int e^x \, dx=e^x+C`, note: '상수 포함' },
  { id: 104, title: '치환적분', latex: String.raw`\int f(g(x))g'(x) \, dx=\int f(u) \, du`, note: '치환' },
  { id: 105, title: '부분적분', latex: String.raw`\int u \, dv=uv-\int v \, du`, note: '부분적분' },
  { id: 106, title: '미분 1', latex: String.raw`\frac{d}{dx}x^n=nx^{n-1}`, note: '미분법' },
  { id: 107, title: '미분 2', latex: String.raw`\frac{d}{dx}\sin x=\cos x`, note: '삼각함수 미분' },
  { id: 108, title: '미분 3', latex: String.raw`\frac{d}{dx}\cos x=-\sin x`, note: '삼각함수 미분' },
  { id: 109, title: '미분 4', latex: String.raw`\frac{d}{dx}e^x=e^x`, note: '지수함수 미분' },
  { id: 110, title: '미분 5', latex: String.raw`\frac{d}{dx}\ln x=\frac{1}{x}`, note: '로그함수 미분' },
  { id: 111, title: '도함수', latex: String.raw`f'(x)=\lim_{h\to 0}\frac{f(x+h)-f(x)}{h}`, note: '정의' },
  { id: 112, title: '적분 1', latex: String.raw`\int_0^\infty e^{-x} \, dx=1`, note: '무한적분' },
  { id: 113, title: '적분 2', latex: String.raw`\int_0^\pi \sin x \, dx=2`, note: '기본 삼각적분' },
  { id: 114, title: '적분 3', latex: String.raw`\int_0^1 \frac{1}{1+x^2} \, dx=\frac{\pi}{4}`, note: '아크탄젠트' },
  { id: 115, title: '극한 1', latex: String.raw`\lim_{x\to 0}\frac{\sin x}{x}=1`, note: '대표 극한', meaning: '사인 함수의 가장 대표적인 기본 극한식이야.' },
  { id: 116, title: '극한 2', latex: String.raw`\lim_{x\to\infty}\frac{2x^2+1}{x^2-3}=2`, note: '유리함수 극한' },
  { id: 117, title: '극한 3', latex: String.raw`\lim_{n\to\infty}\left(1+\frac{1}{n}\right)^n=e`, note: 'e' },
  { id: 118, title: '합 1', latex: String.raw`\sum_{n=1}^{\infty} \frac{1}{n^2}=\frac{\pi^2}{6}`, note: '바젤 문제' },
  { id: 119, title: '합 2', latex: String.raw`\sum_{k=0}^{m} 2^k=2^{m+1}-1`, note: '등비급수' },
  { id: 120, title: '합 3', latex: String.raw`\sum_{i=1}^{n} i=\frac{n(n+1)}{2}`, note: '등차합' },
  { id: 121, title: '합 4', latex: String.raw`\sum_{i=1}^{n} i^2=\frac{n(n+1)(2n+1)}{6}`, note: '제곱합' },
  { id: 122, title: '합 5', latex: String.raw`\prod_{k=1}^{n} k=n!`, note: '곱' },
  { id: 123, title: '로그 적분', latex: String.raw`\int_0^1 \log x \, dx=-1`, note: '로그적분' },
  { id: 124, title: '도함수2', latex: String.raw`\frac{d}{dx}x^{-1}=-x^{-2}`, note: '음수 지수' },
  { id: 125, title: '도함수3', latex: String.raw`\frac{d}{dx}\tan x=\sec^2 x`, note: '탄젠트 미분' },
  { id: 126, title: '연쇄법칙', latex: String.raw`\frac{d}{dx}f(g(x))=f'(g(x))g'(x)`, note: '체인룰' },
  { id: 127, title: '평균값정리', latex: String.raw`f'(c)=\frac{f(b)-f(a)}{b-a}`, note: '평균값정리' },
  { id: 128, title: '테일러 1', latex: String.raw`e^x=\sum_{n=0}^{\infty} \frac{x^n}{n!}`, note: '테일러' },
  { id: 129, title: '테일러 2', latex: String.raw`\sin x=\sum_{n=0}^{\infty} \frac{(-1)^n x^{2n+1}}{(2n+1)!}`, note: '사인 급수' },
  { id: 130, title: '테일러 3', latex: String.raw`\cos x=\sum_{n=0}^{\infty} \frac{(-1)^n x^{2n}}{(2n)!}`, note: '코사인 급수' },
  { id: 131, title: '로피탈', latex: String.raw`\lim_{x\to 0}\frac{1-\cos x}{x^2}=\frac{1}{2}`, note: '극한' },
  { id: 132, title: '미분방정식 1', latex: String.raw`\frac{dy}{dx}=ky`, note: '성장모형' },
  { id: 133, title: '미분방정식 2', latex: String.raw`\frac{dy}{dx}+y=e^x`, note: '선형 ODE' },
  { id: 134, title: '미분방정식 3', latex: String.raw`\frac{
partial u}{
partial t}=\alpha \frac{
partial^2 u}{
partial x^2}`, note: '열방정식' },
  { id: 135, title: '미분방정식 4', latex: String.raw`\frac{
partial^2 u}{
partial t^2}=c^2\frac{
partial^2 u}{
partial x^2}`, note: '파동방정식' },
  { id: 136, title: '벡터미적분 1', latex: String.raw`\nabla \cdot \mathbf{F}=\frac{
partial F_x}{
partial x}+\frac{
partial F_y}{
partial y}`, note: '발산' },
  { id: 137, title: '벡터미적분 2', latex: String.raw`\nabla \times \mathbf{F}`, note: '회전' },
  { id: 138, title: '벡터미적분 3', latex: String.raw`\oint_C P \, dx+Q \, dy`, note: '선적분' },
  { id: 139, title: '정적분4', latex: String.raw`\int_{0}^{\pi} \sin^2 x \, dx=\frac{\pi}{2}`, note: '삼각적분' },
  { id: 140, title: '정적분5', latex: String.raw`\int_{-1}^{1} x^3 \, dx=0`, note: '홀함수' },
  { id: 141, title: '정적분6', latex: String.raw`\int_{0}^{1} x \, dx=\frac{1}{2}`, note: '기본 적분' },
  { id: 142, title: '정적분7', latex: String.raw`\int_{0}^{1} x^2 \, dx=\frac{1}{3}`, note: '기본 적분' },
  { id: 143, title: '정적분8', latex: String.raw`\int_{0}^{1} x^3 \, dx=\frac{1}{4}`, note: '기본 적분' },
  { id: 144, title: '정적분9', latex: String.raw`\int_{0}^{1} \sqrt{x} \, dx=\frac{2}{3}`, note: '루트 적분' },
  { id: 145, title: '정적분10', latex: String.raw`\int_{0}^{1} \frac{1}{1+x} \, dx=\ln 2`, note: '로그 적분' },
  { id: 146, title: '극한4', latex: String.raw`\lim_{x\to 0}\frac{e^x-1}{x}=1`, note: '지수 극한' },
  { id: 147, title: '극한5', latex: String.raw`\lim_{x\to 0}\frac{\ln(1+x)}{x}=1`, note: '로그 극한' },
  { id: 148, title: '극한6', latex: String.raw`\lim_{x\to 0}\frac{\tan x}{x}=1`, note: '탄젠트 극한' },
  { id: 149, title: '급수1', latex: String.raw`\sum_{n=0}^{\infty} ar^n=\frac{a}{1-r}`, note: '등비급수' },
  { id: 150, title: '적분 종합', latex: String.raw`\int_{0}^{1} \frac{x^n}{1+x^2} \, dx`, note: '종합' },
])

const linearAlgebra = makeCategory('선형대수', [
  { id: 201, title: '행렬 1', latex: String.raw`\begin{bmatrix} a & b \\ c & d \end{bmatrix}`, note: '2x2 행렬' },
  { id: 202, title: '행렬 2', latex: String.raw`\begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix}`, note: '단위행렬' },
  { id: 203, title: '벡터 1', latex: String.raw`\vec{v}=\begin{bmatrix} x \\ y \\ z \end{bmatrix}`, note: '벡터와 행렬' },
  { id: 204, title: '벡터 2', latex: String.raw`\|x\|_2=\sqrt{\sum_{i=1}^{n} x_i^2}`, note: '노름', meaning: '벡터 x의 유클리드 길이, 즉 L2 노름을 뜻해.' },
  { id: 205, title: '내적', latex: String.raw`\langle u,v \rangle = \sum_{i=1}^{n} u_i v_i`, note: '내적' },
  { id: 206, title: '고유값', latex: String.raw`A\mathbf{x}=\lambda\mathbf{x}`, note: '고유값' },
  { id: 207, title: '대각화', latex: String.raw`A=PDP^{-1}`, note: '대각화' },
  { id: 208, title: '역행렬', latex: String.raw`A^{-1}A=I`, note: '역행렬' },
  { id: 209, title: '전치', latex: String.raw`A^T=(a_{ji})`, note: '전치행렬' },
  { id: 210, title: '행렬식 1', latex: String.raw`\det\begin{bmatrix} a & b \\ c & d \end{bmatrix}=ad-bc`, note: '행렬식' },
  { id: 211, title: '행렬식 2', latex: String.raw`\det(AB)=\det(A)\det(B)`, note: '곱셈 법칙' },
  { id: 212, title: '랭크', latex: String.raw`\operatorname{rank}(A)`, note: '랭크' },
  { id: 213, title: '정사영', latex: String.raw`\operatorname{proj}_u v`, note: '정사영' },
  { id: 214, title: 'Gram-Schmidt', latex: String.raw`u_i=v_i-\sum_{j=1}^{i-1} \operatorname{proj}_{u_j} v_i`, note: '정규직교화' },
  { id: 215, title: '기저', latex: String.raw`\{e_1,e_2,e_3\}`, note: '기저' },
  { id: 216, title: '선형결합', latex: String.raw`a_1v_1+a_2v_2+\cdots+a_nv_n`, note: '선형결합' },
  { id: 217, title: '선형독립', latex: String.raw`c_1v_1+\cdots+c_nv_n=0`, note: '독립성' },
  { id: 218, title: '기본공간', latex: String.raw`\operatorname{Null}(A)`, note: '영공간' },
  { id: 219, title: '열공간', latex: String.raw`\operatorname{Col}(A)`, note: '열공간' },
  { id: 220, title: '행공간', latex: String.raw`\operatorname{Row}(A)`, note: '행공간' },
  { id: 221, title: 'SVD', latex: String.raw`A=U\Sigma V^T`, note: '특이값분해' },
  { id: 222, title: '투영행렬', latex: String.raw`P=A(A^TA)^{-1}A^T`, note: '투영' },
  { id: 223, title: '직교행렬', latex: String.raw`Q^TQ=I`, note: '직교' },
  { id: 224, title: '대칭행렬', latex: String.raw`A=A^T`, note: '대칭' },
  { id: 225, title: '고유벡터', latex: String.raw`A\mathbf{v}=\lambda\mathbf{v}`, note: '고유벡터' },
  { id: 226, title: '이차형식', latex: String.raw`x^TAx`, note: '이차형식' },
  { id: 227, title: '랭크-널리티', latex: String.raw`\operatorname{rank}(A)+\operatorname{nullity}(A)=n`, note: '랭크-널리티' },
  { id: 228, title: '선형시스템', latex: String.raw`A\mathbf{x}=\mathbf{b}`, note: '선형시스템' },
  { id: 229, title: '가우스 소거', latex: String.raw`\begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}`, note: '소거법' },
  { id: 230, title: '블록행렬', latex: String.raw`\begin{bmatrix} A & B \\ C & D \end{bmatrix}`, note: '블록 행렬' },
  { id: 231, title: '선형변환 1', latex: String.raw`T(\mathbf{x})=A\mathbf{x}`, note: '선형변환' },
  { id: 232, title: '선형변환 2', latex: String.raw`T(\mathbf{u}+\mathbf{v})=T(\mathbf{u})+T(\mathbf{v})`, note: '가법성' },
  { id: 233, title: '선형변환 3', latex: String.raw`T(c\mathbf{x})=cT(\mathbf{x})`, note: '동차성' },
  { id: 234, title: '내적공간', latex: String.raw`\langle x,y \rangle = x^Ty`, note: '내적공간' },
  { id: 235, title: '코시슈바르츠', latex: String.raw`|x^Ty|\le \|x\|_2\|y\|_2`, note: '부등식' },
  { id: 236, title: '벡터합', latex: String.raw`\mathbf{u}+\mathbf{v}`, note: '벡터합' },
  { id: 237, title: '벡터차', latex: String.raw`\mathbf{u}-\mathbf{v}`, note: '벡터차' },
  { id: 238, title: '기저변환', latex: String.raw`[x]_B=P^{-1}x`, note: '기저변환' },
  { id: 239, title: '공간차원', latex: String.raw`\dim V=n`, note: '차원' },
  { id: 240, title: '복소벡터', latex: String.raw`\mathbf{z}\in\mathbb{C}^n`, note: '복소벡터' },
  { id: 241, title: '직교분해', latex: String.raw`x=\hat{x}+e`, note: '직교분해' },
  { id: 242, title: '정규직교', latex: String.raw`Q^TQ=I`, note: '정규직교' },
  { id: 243, title: '행렬곱', latex: String.raw`(AB)_{ij}=\sum_k a_{ik}b_{kj}`, note: '행렬곱' },
  { id: 244, title: '행렬곱2', latex: String.raw`AB\neq BA`, note: '비가환성' },
  { id: 245, title: '고유다항식', latex: String.raw`\det(A-\lambda I)=0`, note: '고유다항식' },
  { id: 246, title: '직접합', latex: String.raw`V\oplus W`, note: '직접합' },
  { id: 247, title: '공간합', latex: String.raw`U+W`, note: '부분공간 합' },
  { id: 248, title: '선형독립2', latex: String.raw`\alpha_1v_1+\cdots+\alpha_kv_k=0`, note: '독립성' },
  { id: 249, title: '랭크2', latex: String.raw`\operatorname{rank}(A)=r`, note: '랭크' },
  { id: 250, title: '선형대수 종합', latex: String.raw`A=Q\Lambda Q^T`, note: '대칭행렬 대각화' },
])

const electromagnetism = makeCategory('전자기학', [
  { id: 301, title: '가우스 법칙', latex: String.raw`\nabla \cdot \mathbf{E}=\frac{\rho}{\varepsilon_0}`, note: '전기장 발산', meaning: '전하 밀도가 전기장의 발산을 만든다는 맥스웰 방정식이야.' },
  { id: 302, title: '자기 가우스 법칙', latex: String.raw`\nabla \cdot \mathbf{B}=0`, note: '자기 단극자 없음' },
  { id: 303, title: '패러데이 법칙', latex: String.raw`\nabla \times \mathbf{E}=-\frac{\partial \mathbf{B}}{\partial t}`, note: '유도 전기장' },
  { id: 304, title: '암페어-맥스웰', latex: String.raw`\nabla \times \mathbf{B}=\mu_0\mathbf{J}+\mu_0\varepsilon_0\frac{\partial \mathbf{E}}{\partial t}`, note: '변위전류 포함' },
  { id: 305, title: '쿨롱 법칙', latex: String.raw`\mathbf{F}=\frac{1}{4\pi\varepsilon_0}\frac{q_1q_2}{r^2}\hat{\mathbf{r}}`, note: '쿨롱 힘' },
  { id: 306, title: '로렌츠 힘', latex: String.raw`\mathbf{F}=q(\mathbf{E}+\mathbf{v}\times\mathbf{B})`, note: '로렌츠 힘' },
  { id: 307, title: '전위 정의', latex: String.raw`\mathbf{E}=-\nabla V`, note: '스칼라 퍼텐셜' },
  { id: 308, title: '벡터퍼텐셜', latex: String.raw`\mathbf{B}=\nabla\times\mathbf{A}`, note: '벡터 퍼텐셜' },
  { id: 309, title: '포아송 방정식', latex: String.raw`\nabla^2 V=-\frac{\rho}{\varepsilon_0}`, note: '정전기' },
  { id: 310, title: '라플라스 방정식', latex: String.raw`\nabla^2 V=0`, note: '무전하 영역' },
  { id: 311, title: '전기력선속', latex: String.raw`\oint_S \mathbf{E}\cdot d\mathbf{A}=\frac{Q_{\mathrm{enc}}}{\varepsilon_0}`, note: '적분형 가우스 법칙' },
  { id: 312, title: '자기력선속', latex: String.raw`\oint_S \mathbf{B}\cdot d\mathbf{A}=0`, note: '적분형' },
  { id: 313, title: '패러데이 적분형', latex: String.raw`\oint_C \mathbf{E}\cdot d\mathbf{l}=-\frac{d\Phi_B}{dt}`, note: '전자기 유도' },
  { id: 314, title: '암페어 적분형', latex: String.raw`\oint_C \mathbf{B}\cdot d\mathbf{l}=\mu_0 I_{\mathrm{enc}}+\mu_0\varepsilon_0\frac{d\Phi_E}{dt}`, note: '순환 적분' },
  { id: 315, title: '파동방정식 E', latex: String.raw`\nabla^2 \mathbf{E}-\mu_0\varepsilon_0\frac{\partial^2 \mathbf{E}}{\partial t^2}=0`, note: '전자기파' },
  { id: 316, title: '파동방정식 B', latex: String.raw`\nabla^2 \mathbf{B}-\mu_0\varepsilon_0\frac{\partial^2 \mathbf{B}}{\partial t^2}=0`, note: '전자기파' },
  { id: 317, title: '파동속도', latex: String.raw`c=\frac{1}{\sqrt{\mu_0\varepsilon_0}}`, note: '광속' },
  { id: 318, title: '포인팅 벡터', latex: String.raw`\mathbf{S}=\frac{1}{\mu_0}\mathbf{E}\times\mathbf{B}`, note: '에너지 흐름' },
  { id: 319, title: '에너지 밀도', latex: String.raw`u=\frac{1}{2}\varepsilon_0 E^2+\frac{1}{2\mu_0}B^2`, note: '장 에너지' },
  { id: 320, title: '비오-사바르', latex: String.raw`d\mathbf{B}=\frac{\mu_0}{4\pi}\frac{I d\mathbf{l}\times\hat{\mathbf{r}}}{r^2}`, note: '전류 자기장' },
  { id: 321, title: '직선도선 자기장', latex: String.raw`B=\frac{\mu_0 I}{2\pi r}`, note: '직선도선' },
  { id: 322, title: '원형코일 중심', latex: String.raw`B=\frac{\mu_0 I}{2R}`, note: '원형 루프' },
  { id: 323, title: '솔레노이드', latex: String.raw`B=\mu_0 n I`, note: '이상 솔레노이드' },
  { id: 324, title: '축전기 에너지', latex: String.raw`U=\frac{1}{2}CV^2`, note: '축전기' },
  { id: 325, title: '축전기 전하', latex: String.raw`Q=CV`, note: '축전기 기본' },
  { id: 326, title: '평행판 전기장', latex: String.raw`E=\frac{\sigma}{\varepsilon_0}`, note: '평행판' },
  { id: 327, title: '전위차', latex: String.raw`\Delta V=-\int_a^b \mathbf{E}\cdot d\mathbf{l}`, note: '전위차' },
  { id: 328, title: '전류밀도', latex: String.raw`\mathbf{J}=\sigma\mathbf{E}`, note: '옴 법칙 미분형' },
  { id: 329, title: '저항', latex: String.raw`R=\rho\frac{L}{A}`, note: '재료 저항' },
  { id: 330, title: '전력', latex: String.raw`P=IV`, note: '전력' },
  { id: 331, title: '전력2', latex: String.raw`P=I^2R`, note: '저항손실' },
  { id: 332, title: '자속', latex: String.raw`\Phi_B=\int_S \mathbf{B}\cdot d\mathbf{A}`, note: '자기 선속' },
  { id: 333, title: '전속', latex: String.raw`\Phi_E=\int_S \mathbf{E}\cdot d\mathbf{A}`, note: '전기 선속' },
  { id: 334, title: '유도기전력', latex: String.raw`\mathcal{E}=-\frac{d\Phi_B}{dt}`, note: '패러데이' },
  { id: 335, title: '인덕터', latex: String.raw`V=L\frac{dI}{dt}`, note: '인덕턴스' },
  { id: 336, title: '인덕터 에너지', latex: String.raw`U=\frac{1}{2}LI^2`, note: '자기 에너지' },
  { id: 337, title: 'RC 회로', latex: String.raw`q(t)=CV\left(1-e^{-t/RC}\right)`, note: '충전' },
  { id: 338, title: 'RL 회로', latex: String.raw`I(t)=\frac{V}{R}\left(1-e^{-Rt/L}\right)`, note: '전류 증가' },
  { id: 339, title: 'LC 진동', latex: String.raw`\omega=\frac{1}{\sqrt{LC}}`, note: '자유진동' },
  { id: 340, title: 'RLC 감쇠', latex: String.raw`L\frac{d^2q}{dt^2}+R\frac{dq}{dt}+\frac{q}{C}=0`, note: 'RLC 회로' },
  { id: 341, title: '경계조건 E', latex: String.raw`\hat{\mathbf{n}}\cdot(\mathbf{E}_2-\mathbf{E}_1)=\frac{\sigma_f}{\varepsilon_0}`, note: '법선 성분' },
  { id: 342, title: '경계조건 B', latex: String.raw`\hat{\mathbf{n}}\cdot(\mathbf{B}_2-\mathbf{B}_1)=0`, note: '자기장 법선' },
  { id: 343, title: '경계조건 H', latex: String.raw`\hat{\mathbf{n}}\times(\mathbf{H}_2-\mathbf{H}_1)=\mathbf{K}_f`, note: '접선 성분' },
  { id: 344, title: '유전변위', latex: String.raw`\mathbf{D}=\varepsilon \mathbf{E}`, note: '매질 응답' },
  { id: 345, title: '자기장세기', latex: String.raw`\mathbf{B}=\mu \mathbf{H}`, note: '매질 응답' },
  { id: 346, title: '분극', latex: String.raw`\mathbf{P}=\varepsilon_0\chi_e\mathbf{E}`, note: '분극' },
  { id: 347, title: '자화', latex: String.raw`\mathbf{M}=\chi_m\mathbf{H}`, note: '자화' },
  { id: 348, title: '편파', latex: String.raw`\mathbf{E}(z,t)=E_0\cos(kz-\omega t)\hat{\mathbf{x}}`, note: '평면파' },
  { id: 349, title: '복소 표현', latex: String.raw`\tilde{E}(z,t)=E_0 e^{i(kz-\omega t)}`, note: '복소수 파동' },
  { id: 350, title: '전자기학 종합', latex: String.raw`\nabla\times(\nabla\times\mathbf{E})=-\mu_0\frac{\partial \mathbf{J}}{\partial t}-\mu_0\varepsilon_0\frac{\partial^2 \mathbf{E}}{\partial t^2}`, note: '맥스웰 종합' },
])

const quantum = makeCategory('양자역학', [
  { id: 401, title: '브라켓 1', latex: String.raw`\langle \psi | \phi \rangle`, note: '내적' },
  { id: 402, title: '파동함수', latex: String.raw`\Psi(x,t)=Ae^{i(kx-\omega t)}`, note: '파동함수' },
  { id: 403, title: '정규화', latex: String.raw`\int |\psi|^2 \, dx=1`, note: '정규화' },
  { id: 404, title: '슈뢰딩거', latex: String.raw`i\hbar \frac{\partial}{\partial t}\Psi=\hat{H}\Psi`, note: '시간의존 슈뢰딩거 방정식', meaning: '양자상태가 시간에 따라 어떻게 변하는지 보여주는 핵심 방정식이야.' },
  { id: 405, title: '운동량 연산자', latex: String.raw`\hat{p}=-i\hbar\nabla`, note: '연산자' },
  { id: 406, title: '에너지 연산자', latex: String.raw`\hat{E}=i\hbar\frac{\partial}{\partial t}`, note: '에너지 연산자' },
  { id: 407, title: '기댓값', latex: String.raw`\langle A\rangle=\int \psi^* \hat{A} \psi \, dx`, note: '기댓값' },
  { id: 408, title: '정준교환', latex: String.raw`[\hat{x},\hat{p}]=i\hbar`, note: '교환자' },
  { id: 409, title: '불확정성', latex: String.raw`\Delta x\Delta p\ge \frac{\hbar}{2}`, note: '불확정성 원리' },
  { id: 410, title: '상태중첩', latex: String.raw`|\psi\rangle=c_1|0\rangle+c_2|1\rangle`, note: '중첩' },
  { id: 411, title: '측정확률', latex: String.raw`P(a_i)=|\langle a_i|\psi\rangle|^2`, note: '측정 확률' },
  { id: 412, title: '밀도행렬', latex: String.raw`\rho=\sum_i p_i|\psi_i\rangle\langle\psi_i|`, note: '밀도행렬' },
  { id: 413, title: '유니터리', latex: String.raw`U^\dagger U=I`, note: '유니터리' },
  { id: 414, title: '에르미트', latex: String.raw`\hat{A}^\dagger=\hat{A}`, note: '에르미트' },
  { id: 415, title: '고유값 문제', latex: String.raw`\hat{H}|n\rangle=E_n|n\rangle`, note: '고유상태' },
  { id: 416, title: '조화진동자', latex: String.raw`E_n=\hbar\omega\left(n+\frac{1}{2}\right)`, note: '에너지 준위' },
  { id: 417, title: '스핀 1', latex: String.raw`\mathbf{S}=\frac{\hbar}{2}\boldsymbol{\sigma}`, note: '스핀' },
  { id: 418, title: '파울리', latex: String.raw`\sigma_x\sigma_y=i\sigma_z`, note: '파울리 행렬' },
  { id: 419, title: '터널링', latex: String.raw`T\sim e^{-2\kappa a}`, note: '터널링' },
  { id: 420, title: '보른 규칙', latex: String.raw`|\psi|^2=\psi^*\psi`, note: '확률밀도' },
  { id: 421, title: '히젠베르크', latex: String.raw`\dot{\hat{A}}=\frac{i}{\hbar}[\hat{H},\hat{A}]`, note: '운동방정식' },
  { id: 422, title: '코히런스', latex: String.raw`\langle 0|1\rangle=0`, note: '직교성' },
  { id: 423, title: '토마스-페르미', latex: String.raw`E_F=\frac{\hbar^2}{2m}(3\pi^2 n)^{2/3}`, note: '페르미 에너지' },
  { id: 424, title: '1차원 우물', latex: String.raw`\psi_n(x)=\sqrt{\frac{2}{L}}\sin\frac{n\pi x}{L}`, note: '입자상자' },
  { id: 425, title: '기저전개', latex: String.raw`|\psi\rangle=\sum_n c_n|n\rangle`, note: '전개' },
  { id: 426, title: '전이확률', latex: String.raw`P_{m\to n}=|\langle n|U|m\rangle|^2`, note: '전이' },
  { id: 427, title: '하이젠베르크 그림', latex: String.raw`A_H(t)=e^{i\hat{H}t/\hbar}Ae^{-i\hat{H}t/\hbar}`, note: '그림 전환' },
  { id: 428, title: '라만', latex: String.raw`\omega=\omega_0\pm\Omega`, note: '주파수 분리' },
  { id: 429, title: '양자장', latex: String.raw`[a,a^\dagger]=1`, note: '생성 소멸' },
  { id: 430, title: '양자 얽힘', latex: String.raw`|\Phi^+\rangle=\frac{1}{\sqrt{2}}(|00\rangle+|11\rangle)`, note: '벨 상태' },
  { id: 431, title: '스핀 상태', latex: String.raw`|\uparrow\rangle,|\downarrow\rangle`, note: '스핀 상태' },
  { id: 432, title: '헬름홀츠', latex: String.raw`\hat{H}\psi=E\psi`, note: '시간독립' },
  { id: 433, title: '디랙 노테이션', latex: String.raw`\langle \psi|\hat{A}|\psi\rangle`, note: '기댓값' },
  { id: 434, title: '시간발전', latex: String.raw`|\psi(t)\rangle=U(t)|\psi(0)\rangle`, note: '시간발전' },
  { id: 435, title: '연산자 기대', latex: String.raw`\langle\hat{A}\rangle=\operatorname{Tr}(\rho\hat{A})`, note: 'trace' },
  { id: 436, title: '밀도행렬2', latex: String.raw`\rho^2=\rho`, note: '순수상태' },
  { id: 437, title: '위상', latex: String.raw`e^{i\theta}`, note: '위상인자' },
  { id: 438, title: '확률진폭', latex: String.raw`\mathcal{A}=\langle f|i\rangle`, note: '확률진폭' },
  { id: 439, title: '관측', latex: String.raw`\hat{O}|o\rangle=o|o\rangle`, note: '관측량' },
  { id: 440, title: '양자 종합', latex: String.raw`\hat{H}|\psi\rangle=E|\psi\rangle`, note: '종합' },
  { id: 441, title: '스피너', latex: String.raw`\chi=\begin{bmatrix} a \\ b \end{bmatrix}`, note: '스피너' },
  { id: 442, title: '정준정규화', latex: String.raw`\langle n|m\rangle=\delta_{nm}`, note: '크로네커 델타' },
  { id: 443, title: '기댓값2', latex: String.raw`\langle x\rangle=\int x|\psi|^2 \, dx`, note: '기댓값' },
  { id: 444, title: '오퍼레이터', latex: String.raw`[\hat{x},\hat{p}]_-=i\hbar`, note: '교환자' },
  { id: 445, title: '양자 회로', latex: String.raw`H|0\rangle=\frac{1}{\sqrt{2}}(|0\rangle+|1\rangle)`, note: 'Hadamard' },
  { id: 446, title: '복합상태', latex: String.raw`|\psi\rangle=\alpha|0\rangle+\beta|1\rangle`, note: '복합상태' },
  { id: 447, title: '관측확률', latex: String.raw`p_n=|c_n|^2`, note: '확률' },
  { id: 448, title: '유니터리2', latex: String.raw`U^{\dagger}U=I`, note: '유니터리' },
  { id: 449, title: '고유상태', latex: String.raw`\hat{A}|a\rangle=a|a\rangle`, note: '고유값' },
  { id: 450, title: '양자마무리', latex: String.raw`\sum_n |c_n|^2=1`, note: '정규화' },
])

const statistics = makeCategory('확률통계', [
  { id: 501, title: '기댓값 1', latex: String.raw`E[X]=\sum_x x p(x)`, note: '기댓값 정의' },
  { id: 502, title: '분산 1', latex: String.raw`\operatorname{Var}(X)=E[X^2]-E[X]^2`, note: '분산 정의' },
  { id: 503, title: '공분산', latex: String.raw`\operatorname{Cov}(X,Y)=E[XY]-E[X]E[Y]`, note: '공분산' },
  { id: 504, title: '조건부확률', latex: String.raw`P(A\mid B)=\frac{P(A\cap B)}{P(B)}`, note: '조건부' },
  { id: 505, title: '베이즈', latex: String.raw`P(A\mid B)=\frac{P(B\mid A)P(A)}{P(B)}`, note: '베이즈 정리', meaning: '관측 B가 주어졌을 때 A의 확률을 갱신하는 공식이야.' },
  { id: 506, title: '확률질량', latex: String.raw`\sum_x p(x)=1`, note: '정규화' },
  { id: 507, title: '연속확률', latex: String.raw`\int_{-\infty}^{\infty} f(x) \, dx=1`, note: '밀도함수' },
  { id: 508, title: '정규분포 1', latex: String.raw`f(x)=\frac{1}{\sqrt{2\pi\sigma^2}}e^{-\frac{(x-\mu)^2}{2\sigma^2}}`, note: '정규분포' },
  { id: 509, title: '표준화', latex: String.raw`z=\frac{x-\mu}{\sigma}`, note: 'z-score' },
  { id: 510, title: '표본평균', latex: String.raw`\bar{x}=\frac{1}{n}\sum_{i=1}^{n}x_i`, note: '표본평균' },
  { id: 511, title: '표본분산', latex: String.raw`s^2=\frac{1}{n-1}\sum_{i=1}^{n}(x_i-\bar{x})^2`, note: '표본분산' },
  { id: 512, title: '중앙값', latex: String.raw`\operatorname{median}(x_1,\dots,x_n)`, note: '중앙값' },
  { id: 513, title: '최빈값', latex: String.raw`\operatorname{mode}(X)`, note: '최빈값' },
  { id: 514, title: '확률변수', latex: String.raw`X\sim \operatorname{Bernoulli}(p)`, note: '베르누이' },
  { id: 515, title: '이항분포', latex: String.raw`X\sim \operatorname{Binomial}(n,p)`, note: '이항분포' },
  { id: 516, title: '포아송', latex: String.raw`X\sim \operatorname{Poisson}(\lambda)`, note: '포아송 분포' },
  { id: 517, title: '지수분포', latex: String.raw`f(x)=\lambda e^{-\lambda x}`, note: '지수분포' },
  { id: 518, title: '균등분포', latex: String.raw`X\sim U(a,b)`, note: '균등분포' },
  { id: 519, title: '연속형 기댓값', latex: String.raw`E[g(X)]=\int g(x)f(x) \, dx`, note: '기댓값' },
  { id: 520, title: '모멘트', latex: String.raw`\mu'_k=E[X^k]`, note: '모멘트' },
  { id: 521, title: '상관계수', latex: String.raw`\rho_{XY}=\frac{\operatorname{Cov}(X,Y)}{\sigma_X\sigma_Y}`, note: '상관계수' },
  { id: 522, title: '체비쇼프', latex: String.raw`P(|X-\mu|\ge k\sigma)\le \frac{1}{k^2}`, note: '체비쇼프 부등식' },
  { id: 523, title: '마코프', latex: String.raw`P(X\ge a)\le \frac{E[X]}{a}`, note: '마코프 부등식' },
  { id: 524, title: '대수법칙', latex: String.raw`\bar{X}_n\to \mu`, note: '대수의 법칙' },
  { id: 525, title: '중심극한', latex: String.raw`\frac{\bar{X}_n-\mu}{\sigma/\sqrt{n}}\Rightarrow N(0,1)`, note: '중심극한정리' },
  { id: 526, title: '신뢰구간', latex: String.raw`\bar{x}\pm z_{\alpha/2}\frac{\sigma}{\sqrt{n}}`, note: '신뢰구간' },
  { id: 527, title: '가설검정', latex: String.raw`H_0: \mu=\mu_0`, note: '귀무가설' },
  { id: 528, title: 'p-value', latex: String.raw`p\text{-value}<0.05`, note: '유의수준' },
  { id: 529, title: '카이제곱', latex: String.raw`\chi^2=\sum \frac{(O-E)^2}{E}`, note: '카이제곱' },
  { id: 530, title: '자유도', latex: String.raw`\operatorname{df}=n-1`, note: '자유도' },
  { id: 531, title: '회귀식', latex: String.raw`y=\beta_0+\beta_1x+\varepsilon`, note: '선형회귀' },
  { id: 532, title: '잔차', latex: String.raw`e_i=y_i-\hat{y}_i`, note: '잔차' },
  { id: 533, title: '상관', latex: String.raw`r=\frac{\sum(x_i-\bar{x})(y_i-\bar{y})}{\sqrt{\sum(x_i-\bar{x})^2\sum(y_i-\bar{y})^2}}`, note: '피어슨 상관' },
  { id: 534, title: '분위수', latex: String.raw`Q_p`, note: '분위수' },
  { id: 535, title: '누적분포', latex: String.raw`F(x)=P(X\le x)`, note: 'CDF' },
  { id: 536, title: '생존함수', latex: String.raw`S(x)=1-F(x)`, note: 'survival' },
  { id: 537, title: '밀도', latex: String.raw`f_X(x)`, note: 'pdf' },
  { id: 538, title: '마진분포', latex: String.raw`f_X(x)=\int f_{X,Y}(x,y) \, dy`, note: '마진' },
  { id: 539, title: '조건부밀도', latex: String.raw`f_{X|Y}(x|y)=\frac{f_{X,Y}(x,y)}{f_Y(y)}`, note: '조건부밀도' },
  { id: 540, title: '상호정보', latex: String.raw`I(X;Y)=H(X)+H(Y)-H(X,Y)`, note: '상호정보' },
  { id: 541, title: '엔트로피', latex: String.raw`H(X)=-\sum_x p(x)\log p(x)`, note: '엔트로피' },
  { id: 542, title: 'KL 발산', latex: String.raw`D_{KL}(P\|Q)=\sum_x P(x)\log\frac{P(x)}{Q(x)}`, note: 'KL' },
  { id: 543, title: '우도', latex: String.raw`L(\theta)=\prod_i f(x_i\mid\theta)`, note: '우도함수' },
  { id: 544, title: '로그우도', latex: String.raw`\ell(\theta)=\sum_i \log f(x_i\mid\theta)`, note: '로그우도' },
  { id: 545, title: '포아송 평균', latex: String.raw`E[X]=\lambda`, note: '평균' },
  { id: 546, title: '이항 평균', latex: String.raw`E[X]=np`, note: '이항 평균' },
  { id: 547, title: '이항분산', latex: String.raw`\operatorname{Var}(X)=np(1-p)`, note: '이항 분산' },
  { id: 548, title: '포아송 분산', latex: String.raw`\operatorname{Var}(X)=\lambda`, note: '포아송 분산' },
  { id: 549, title: '기하분포', latex: String.raw`P(X=k)=(1-p)^{k-1}p`, note: '기하분포' },
  { id: 550, title: '확률통계 종합', latex: String.raw`P(A\mid B)=\frac{P(B\mid A)P(A)}{P(B)}`, note: '종합' },
])

const differentialGeometry = makeCategory('미분기하', [
  { id: 601, title: '계량 1', latex: String.raw`ds^2=g_{ij}dx^idx^j`, note: '계량 텐서' },
  { id: 602, title: '크리스토펠', latex: String.raw`\Gamma^k_{ij}=\frac{1}{2}g^{k\ell}(\partial_i g_{j\ell}+\partial_j g_{i\ell}-\partial_\ell g_{ij})`, note: '연결계수', meaning: '곡면이나 시공간에서 방향미분을 정의할 때 쓰는 연결계수야.' },
  { id: 603, title: '공변미분', latex: String.raw`\nabla_i V^j=\partial_i V^j+\Gamma^j_{ik}V^k`, note: '공변미분' },
  { id: 604, title: '곡률', latex: String.raw`R^\rho_{\sigma\mu\nu}=\partial_\mu\Gamma^\rho_{\nu\sigma}-\partial_\nu\Gamma^\rho_{\mu\sigma}+\cdots`, note: '리만 곡률' },
  { id: 605, title: '리치 텐서', latex: String.raw`R_{\mu\nu}=R^\rho_{\mu\rho\nu}`, note: 'Ricci' },
  { id: 606, title: '스칼라 곡률', latex: String.raw`R=g^{\mu\nu}R_{\mu\nu}`, note: '스칼라 곡률' },
  { id: 607, title: '지오데식', latex: String.raw`\frac{d^2x^\mu}{ds^2}+\Gamma^\mu_{\alpha\beta}\frac{dx^\alpha}{ds}\frac{dx^\beta}{ds}=0`, note: '지오데식' },
  { id: 608, title: '라그랑지안', latex: String.raw`L=g_{ij}\dot{x}^i\dot{x}^j`, note: '기하학적 라그랑지안' },
  { id: 609, title: '수선형식', latex: String.raw`\omega^i_j=\Gamma^i_{jk}dx^k`, note: '연결 1-형식' },
  { id: 610, title: '공형식', latex: String.raw`\alpha=\alpha_i dx^i`, note: '1-형식' },
  { id: 611, title: '쌍대기저', latex: String.raw`\theta^i(e_j)=\delta^i_j`, note: '쌍대공간' },
  { id: 612, title: '외미분', latex: String.raw`d(f\,dg)=df\wedge dg`, note: '외미분' },
  { id: 613, title: '와지', latex: String.raw`dx^i\wedge dx^j=-dx^j\wedge dx^i`, note: '외적' },
  { id: 614, title: '스톡스', latex: String.raw`\int_{\partial M}\omega=\int_M d\omega`, note: '스톡스 정리' },
  { id: 615, title: '발산정리', latex: String.raw`\int_{\partial M}\mathbf{F}\cdot d\mathbf{S}=\int_M \nabla\cdot\mathbf{F} \, dV`, note: '발산정리' },
  { id: 616, title: '공간곡선', latex: String.raw`\mathbf{r}(t)=(x(t),y(t),z(t))`, note: '공간곡선' },
  { id: 617, title: '접벡터', latex: String.raw`\dot{\mathbf{r}}(t)`, note: '접벡터' },
  { id: 618, title: '단위접벡터', latex: String.raw`\mathbf{T}=\frac{\dot{\mathbf{r}}}{\|\dot{\mathbf{r}}\|}`, note: '단위접벡터' },
  { id: 619, title: '곡률2', latex: String.raw`\kappa=\frac{\|\dot{\mathbf{T}}\|}{\|\dot{\mathbf{r}}\|}`, note: '곡률' },
  { id: 620, title: '법선', latex: String.raw`\mathbf{N}=\frac{\dot{\mathbf{T}}}{\|\dot{\mathbf{T}}\|}`, note: '법선벡터' },
  { id: 621, title: '비틀림', latex: String.raw`\tau=\frac{(\dot{\mathbf{r}}\times\ddot{\mathbf{r}})\cdot\dddot{\mathbf{r}}}{\|\dot{\mathbf{r}}\times\ddot{\mathbf{r}}\|^2}`, note: '비틀림' },
  { id: 622, title: '접평면', latex: String.raw`z-z_0=f_x(x_0,y_0)(x-x_0)+f_y(x_0,y_0)(y-y_0)`, note: '접평면' },
  { id: 623, title: '법곡률', latex: String.raw`k_n=\kappa\cos\phi`, note: '법곡률' },
  { id: 624, title: '주곡률', latex: String.raw`k_1,k_2`, note: '주곡률' },
  { id: 625, title: '가우스 곡률', latex: String.raw`K=k_1k_2`, note: '가우스 곡률' },
  { id: 626, title: '평균 곡률', latex: String.raw`H=\frac{k_1+k_2}{2}`, note: '평균 곡률' },
  { id: 627, title: '연결', latex: String.raw`\nabla_XY`, note: '연결' },
  { id: 628, title: '리만기하', latex: String.raw`(M,g)`, note: '리만 다양체' },
  { id: 629, title: '곡면', latex: String.raw`S(u,v)`, note: '매개곡면' },
  { id: 630, title: '면적요소', latex: String.raw`dA=\|S_u\times S_v\| \, du \, dv`, note: '면적 요소' },
  { id: 631, title: '체적요소', latex: String.raw`dV=\sqrt{\det g} \, dx^1dx^2dx^3`, note: '체적 요소' },
  { id: 632, title: '벡터장', latex: String.raw`X=X^i\partial_i`, note: '벡터장' },
  { id: 633, title: '매끄러움', latex: String.raw`f\in C^\infty(M)`, note: '매끄러움' },
  { id: 634, title: '좌표변환', latex: String.raw`x'^i=x'^i(x^1,\dots,x^n)`, note: '좌표변환' },
  { id: 635, title: 'Jacobi', latex: String.raw`J=\frac{\partial(x',y')}{\partial(x,y)}`, note: '자코비안' },
  { id: 636, title: '연결 2', latex: String.raw`\nabla_{\partial_i}\partial_j=\Gamma^k_{ij}\partial_k`, note: '연결' },
  { id: 637, title: '평행이동', latex: String.raw`\nabla_{\dot\gamma}V=0`, note: '평행이동' },
  { id: 638, title: '레비-치비타', latex: String.raw`\nabla g=0`, note: '레비-치비타' },
  { id: 639, title: '곡률텐서', latex: String.raw`R(X,Y)Z`, note: '곡률 텐서' },
  { id: 640, title: '미분기하 종합', latex: String.raw`\Gamma^k_{ij}=\frac{1}{2}g^{k\ell}(\partial_i g_{j\ell}+\partial_j g_{i\ell}-\partial_\ell g_{ij})`, note: '종합' },
])

const machineLearning = makeCategory('머신러닝', [
  { id: 701, title: '선형회귀', latex: String.raw`y=\beta_0+\beta_1x+\varepsilon`, note: '선형회귀' },
  { id: 702, title: '로지스틱', latex: String.raw`\sigma(z)=\frac{1}{1+e^{-z}}`, note: '시그모이드' },
  { id: 703, title: '소프트맥스', latex: String.raw`p_i=\frac{e^{z_i}}{\sum_j e^{z_j}}`, note: 'softmax', meaning: '점수 벡터를 확률분포로 바꿔주는 분류용 함수야.' },
  { id: 704, title: '크로스엔트로피', latex: String.raw`L=-\sum_i y_i\log\hat{y}_i`, note: '손실함수' },
  { id: 705, title: 'MSE', latex: String.raw`\frac{1}{n}\sum_{i=1}^{n}(y_i-\hat{y}_i)^2`, note: '평균제곱오차' },
  { id: 706, title: '정규방정식', latex: String.raw`\hat{\beta}=(X^TX)^{-1}X^Ty`, note: '정규방정식' },
  { id: 707, title: '경사하강법', latex: String.raw`\theta:=\theta-\eta\nabla_\theta J(\theta)`, note: '경사하강' },
  { id: 708, title: '확률적 경사하강', latex: String.raw`\theta_{t+1}=\theta_t-\eta\nabla_\theta \ell_t(\theta_t)`, note: 'SGD' },
  { id: 709, title: '모멘텀', latex: String.raw`v_t=\gamma v_{t-1}+\eta\nabla J(\theta_t)`, note: '모멘텀' },
  { id: 710, title: '배치정규화', latex: String.raw`\hat{x}=\frac{x-\mu}{\sqrt{\sigma^2+\epsilon}}`, note: '배치 정규화' },
  { id: 711, title: '드롭아웃', latex: String.raw`\tilde{h}=m\odot h`, note: '드롭아웃' },
  { id: 712, title: '활성함수1', latex: String.raw`\operatorname{ReLU}(x)=\max(0,x)`, note: 'ReLU' },
  { id: 713, title: '활성함수2', latex: String.raw`\tanh x=\frac{e^x-e^{-x}}{e^x+e^{-x}}`, note: 'tanh' },
  { id: 714, title: '활성함수3', latex: String.raw`\operatorname{GELU}(x)`, note: 'GELU' },
  { id: 715, title: '로스', latex: String.raw`\mathcal{L}(\theta)=\frac{1}{n}\sum_i \ell_i(\theta)`, note: 'loss' },
  { id: 716, title: '정확도', latex: String.raw`\operatorname{Acc}=\frac{\text{correct}}{\text{total}}`, note: '정확도' },
  { id: 717, title: '정밀도', latex: String.raw`\operatorname{Precision}=\frac{TP}{TP+FP}`, note: 'precision' },
  { id: 718, title: '재현율', latex: String.raw`\operatorname{Recall}=\frac{TP}{TP+FN}`, note: 'recall' },
  { id: 719, title: 'F1', latex: String.raw`F_1=\frac{2PR}{P+R}`, note: 'F1' },
  { id: 720, title: 'ROC', latex: String.raw`\operatorname{AUC}`, note: 'AUC' },
  { id: 721, title: '정규화', latex: String.raw`\|w\|_2^2`, note: 'L2 regularization' },
  { id: 722, title: 'L1 정규화', latex: String.raw`\|w\|_1`, note: 'L1 regularization' },
  { id: 723, title: '릿지', latex: String.raw`J=\text{MSE}+\lambda\|w\|_2^2`, note: 'ridge' },
  { id: 724, title: '라쏘', latex: String.raw`J=\text{MSE}+\lambda\|w\|_1`, note: 'lasso' },
  { id: 725, title: '교차엔트로피', latex: String.raw`H(p,q)=-\sum_i p_i\log q_i`, note: 'cross entropy' },
  { id: 726, title: 'KL', latex: String.raw`D_{KL}(p\|q)=\sum_i p_i\log\frac{p_i}{q_i}`, note: 'KL divergence' },
  { id: 727, title: '베이즈 네트워크', latex: String.raw`P(X\mid Y)`, note: '조건부' },
  { id: 728, title: '정규분포2', latex: String.raw`\mathcal{N}(\mu,\sigma^2)`, note: '가우시안' },
  { id: 729, title: '퍼셉트론', latex: String.raw`y=\operatorname{sign}(w^Tx+b)`, note: '퍼셉트론' },
  { id: 730, title: 'SVM', latex: String.raw`\min \frac{1}{2}\|w\|^2`, note: '서포트 벡터 머신' },
  { id: 731, title: '커널', latex: String.raw`k(x,x')=\phi(x)^T\phi(x')`, note: 'kernel trick' },
  { id: 732, title: 'PCA', latex: String.raw`\max_{\|w\|=1} w^TSw`, note: '주성분분석' },
  { id: 733, title: '고유벡터2', latex: String.raw`Sw=\lambda w`, note: 'PCA' },
  { id: 734, title: '정렬손실', latex: String.raw`\max(0,1-yf(x))`, note: 'hinge loss' },
  { id: 735, title: '앤트로피', latex: String.raw`H(X)=-\sum_x p(x)\log p(x)`, note: '정보 엔트로피' },
  { id: 736, title: '샘플링', latex: String.raw`x\sim p_{\theta}(x)`, note: 'sampling' },
  { id: 737, title: '최대우도', latex: String.raw`\hat{\theta}=\arg\max_{\theta}\prod_i p(x_i\mid\theta)`, note: 'MLE' },
  { id: 738, title: '로그우도2', latex: String.raw`\ell(\theta)=\sum_i \log p(x_i\mid\theta)`, note: 'log-likelihood' },
  { id: 739, title: '정규화2', latex: String.raw`x' = \frac{x-\mu}{\sigma}`, note: 'standardization' },
  { id: 740, title: '오차역전파', latex: String.raw`\delta^l=(W^{l+1})^T\delta^{l+1}\odot\sigma'(z^l)`, note: 'backprop' },
  { id: 741, title: '시그모이드미분', latex: String.raw`\sigma'(x)=\sigma(x)(1-\sigma(x))`, note: '미분' },
  { id: 742, title: '리커런트', latex: String.raw`h_t=f(h_{t-1},x_t)`, note: 'RNN' },
  { id: 743, title: '어텐션', latex: String.raw`\operatorname{softmax}(QK^T)V`, note: 'attention' },
  { id: 744, title: '트랜스포머', latex: String.raw`\operatorname{Attention}(Q,K,V)`, note: 'Transformer' },
  { id: 745, title: '임베딩', latex: String.raw`\mathbf{e}_i`, note: 'embedding' },
  { id: 746, title: '엔드투엔드', latex: String.raw`f_\theta(x)`, note: '모델' },
  { id: 747, title: '생성모델', latex: String.raw`p_{\theta}(x)=\sum_z p_{\theta}(x,z)`, note: 'generative' },
  { id: 748, title: '판별모델', latex: String.raw`p_{\theta}(y\mid x)`, note: 'discriminative' },
  { id: 749, title: '토큰화', latex: String.raw`x_{1:T}`, note: 'sequence' },
  { id: 750, title: '머신러닝 종합', latex: String.raw`\arg\min_{\theta} \mathcal{L}(\theta)`, note: '종합' },
])

export const practiceSet = [...algebra, ...calculus, ...linearAlgebra, ...electromagnetism, ...quantum, ...statistics, ...differentialGeometry, ...machineLearning]
export const practiceCategories = ['전체', '대수', '미적분', '선형대수', '전자기학', '양자역학', '확률통계', '미분기하', '머신러닝'] as const
export type PracticeCategory = (typeof practiceCategories)[number]
