export type PracticeItem = {
  id: number
  title: string
  latex: string
  note: string
}

export const practiceSet: PracticeItem[] = [
  { id: 1, title: '기본 분수 1', latex: String.raw`\frac{a+b}{c+d}`, note: '분수 기본기' },
  { id: 2, title: '기본 분수 2', latex: String.raw`\frac{x^2-1}{x+1}`, note: '인수분해가 떠오르는 꼴' },
  { id: 3, title: '연분수 형태', latex: String.raw`1+\frac{1}{1+\frac{1}{x}}`, note: '중첩 분수 읽기' },
  { id: 4, title: '제곱근 1', latex: String.raw`\sqrt{x^2+y^2}`, note: '공백 없는 기본 루트' },
  { id: 5, title: '제곱근 2', latex: String.raw`\sqrt[3]{a^3+b^3}`, note: 'n제곱근 입력' },
  { id: 6, title: '지수와 첨자', latex: String.raw`x_{n+1}=x_n^2+1`, note: '위아래 첨자 섞기' },
  { id: 7, title: '합 기호 1', latex: String.raw`\sum_{i=1}^{n} i^2`, note: '합 기호 기본' },
  { id: 8, title: '합 기호 2', latex: String.raw`\sum_{k=0}^{m} 2^k`, note: '지수형 합' },
  { id: 9, title: '곱 기호', latex: String.raw`\prod_{j=1}^{n} j`, note: 'product 기호' },
  { id: 10, title: '극한 1', latex: String.raw`\lim_{x\to 0} \frac{\sin x}{x}`, note: '고전적 극한식' },
  { id: 11, title: '극한 2', latex: String.raw`\lim_{n\to\infty} \left(1+\frac{1}{n}\right)^n`, note: 'e로 가는 꼴' },
  { id: 12, title: '정적분 1', latex: String.raw`\int_{0}^{1} x^2 \, dx`, note: '간단한 정적분' },
  { id: 13, title: '정적분 2', latex: String.raw`\int_{-\pi}^{\pi} \cos x \, dx`, note: '음수 하한 포함' },
  { id: 14, title: '부정적분', latex: String.raw`\int e^x \, dx = e^x + C`, note: '상수항 포함' },
  { id: 15, title: '편미분', latex: String.raw`\frac{\partial z}{\partial x}=2x+y`, note: 'partial 기호' },
  { id: 16, title: '이중 첨자', latex: String.raw`a_{i,j}=i+j`, note: '콤마가 있는 첨자' },
  { id: 17, title: '행렬 1', latex: String.raw`\begin{bmatrix} a & b \\ c & d \end{bmatrix}`, note: '2x2 행렬' },
  { id: 18, title: '행렬 2', latex: String.raw`\begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix}`, note: '단위행렬' },
  { id: 19, title: '벡터 표기', latex: String.raw`\vec{v}=\begin{bmatrix} x \\ y \\ z \end{bmatrix}`, note: '벡터와 행렬 혼합' },
  { id: 20, title: '절댓값', latex: String.raw`\left| x-y \right|`, note: 'left/right 완화 확인용' },
  { id: 21, title: '집합 포함', latex: String.raw`A \subseteq B \subseteq C`, note: '집합 기호' },
  { id: 22, title: '집합 연산', latex: String.raw`A \cap (B \cup C)`, note: '괄호와 집합 기호' },
  { id: 23, title: '논리 기호', latex: String.raw`P \implies Q \iff \neg Q \implies \neg P`, note: '명제 논리' },
  { id: 24, title: '확률 1', latex: String.raw`P(A \mid B)=\frac{P(A\cap B)}{P(B)}`, note: '조건부확률' },
  { id: 25, title: '확률 2', latex: String.raw`E[X]=\sum_{x} x p(x)`, note: '기댓값 정의' },
  { id: 26, title: '분산', latex: String.raw`\operatorname{Var}(X)=E[X^2]-E[X]^2`, note: 'operatorname 포함' },
  { id: 27, title: '정규분포', latex: String.raw`f(x)=\frac{1}{\sqrt{2\pi\sigma^2}}e^{-\frac{(x-\mu)^2}{2\sigma^2}}`, note: '조금 긴 식' },
  { id: 28, title: '미분방정식', latex: String.raw`\frac{dy}{dx}+y=e^x`, note: '선형 ODE 꼴' },
  { id: 29, title: '삼각함수', latex: String.raw`\sin^2 x + \cos^2 x = 1`, note: '기본 항등식' },
  { id: 30, title: '탄젠트', latex: String.raw`\tan x = \frac{\sin x}{\cos x}`, note: '삼각함수 비율' },
  { id: 31, title: '로그 1', latex: String.raw`\log(ab)=\log a + \log b`, note: '로그 법칙' },
  { id: 32, title: '로그 2', latex: String.raw`\ln(e^x)=x`, note: '자연로그' },
  { id: 33, title: '극좌표', latex: String.raw`x=r\cos\theta,\ y=r\sin\theta`, note: '그리스 문자 포함' },
  { id: 34, title: '복소수 1', latex: String.raw`z=a+bi`, note: '기본 복소수' },
  { id: 35, title: '복소수 2', latex: String.raw`|z|=\sqrt{a^2+b^2}`, note: '복소수 절댓값' },
  { id: 36, title: '오일러 공식', latex: String.raw`e^{i\theta}=\cos\theta+i\sin\theta`, note: '대표 공식' },
  { id: 37, title: '이항정리', latex: String.raw`(x+y)^n=\sum_{k=0}^{n} \binom{n}{k} x^{n-k} y^k`, note: '난이도 조금 상승' },
  { id: 38, title: '조합 1', latex: String.raw`\binom{n}{r}=\frac{n!}{r!(n-r)!}`, note: '조합 공식' },
  { id: 39, title: '조합 2', latex: String.raw`{}_n C_r = \frac{n!}{r!(n-r)!}`, note: '표기 변형' },
  { id: 40, title: '계승', latex: String.raw`n!=\prod_{k=1}^{n} k`, note: '계승과 곱기호' },
  { id: 41, title: '무한급수', latex: String.raw`\sum_{n=0}^{\infty} \frac{x^n}{n!}`, note: '무한대 포함' },
  { id: 42, title: '기하급수', latex: String.raw`\sum_{n=0}^{\infty} ar^n=\frac{a}{1-r}`, note: '수렴형 급수' },
  { id: 43, title: '테일러 1', latex: String.raw`e^x=\sum_{n=0}^{\infty} \frac{x^n}{n!}`, note: '자주 보는 전개' },
  { id: 44, title: '테일러 2', latex: String.raw`\sin x=\sum_{n=0}^{\infty} \frac{(-1)^n x^{2n+1}}{(2n+1)!}`, note: '부호와 지수 조합' },
  { id: 45, title: '푸리에 계수', latex: String.raw`a_n=\frac{1}{\pi}\int_{-\pi}^{\pi} f(x)\cos(nx) \, dx`, note: '조금 더 긴 적분식' },
  { id: 46, title: '라플라스 변환', latex: String.raw`\mathcal{L}\{f(t)\}=\int_{0}^{\infty} e^{-st}f(t) \, dt`, note: '중괄호와 무한대' },
  { id: 47, title: '극한 비교', latex: String.raw`\lim_{x\to\infty} \frac{2x^2+1}{x^2-3}=2`, note: '유리함수 극한' },
  { id: 48, title: '부분합', latex: String.raw`S_n=\sum_{k=1}^{n} a_k`, note: '부분합 기호' },
  { id: 49, title: '수열 점화식', latex: String.raw`a_{n+2}-3a_{n+1}+2a_n=0`, note: '첨자 많은 점화식' },
  { id: 50, title: '극한 정의', latex: String.raw`\forall \varepsilon > 0, \exists N \in \mathbb{N}`, note: '수리논리 느낌' },
  { id: 51, title: '집합 표기', latex: String.raw`\{ x \in \mathbb{R} \mid x^2 < 2 \}`, note: '조건제시 집합' },
  { id: 52, title: '내적', latex: String.raw`\langle u,v \rangle = \sum_{i=1}^{n} u_i v_i`, note: 'angle bracket' },
  { id: 53, title: '노름', latex: String.raw`\|x\|_2=\sqrt{\sum_{i=1}^{n} x_i^2}`, note: '벡터 노름' },
  { id: 54, title: '미분 정의', latex: String.raw`f'(x)=\lim_{h\to 0}\frac{f(x+h)-f(x)}{h}`, note: '도함수 정의' },
  { id: 55, title: '체인룰', latex: String.raw`\frac{d}{dx}f(g(x))=f'(g(x))g'(x)`, note: '합성함수 미분' },
  { id: 56, title: '부분적분', latex: String.raw`\int u \, dv = uv-\int v \, du`, note: '부분적분 공식' },
  { id: 57, title: '치환적분', latex: String.raw`\int f(g(x))g'(x) \, dx = \int f(u) \, du`, note: '변수치환' },
  { id: 58, title: '그린정리 느낌', latex: String.raw`\oint_C P \, dx + Q \, dy`, note: '선적분 표기' },
  { id: 59, title: '발산', latex: String.raw`\nabla \cdot \mathbf{F}=\frac{\partial F_x}{\partial x}+\frac{\partial F_y}{\partial y}`, note: '벡터해석' },
  { id: 60, title: '회전', latex: String.raw`\nabla \times \mathbf{F}`, note: 'curl 표기' },
  { id: 61, title: '델타 함수', latex: String.raw`\delta(x-a)`, note: '간단하지만 특수함수' },
  { id: 62, title: '브라켓', latex: String.raw`\langle \psi | \phi \rangle`, note: '양자역학 표기' },
  { id: 63, title: '슈뢰딩거', latex: String.raw`i\hbar \frac{\partial}{\partial t}\Psi = \hat{H}\Psi`, note: '물리식' },
  { id: 64, title: '맥스웰 1', latex: String.raw`\nabla \cdot \mathbf{E}=\frac{\rho}{\varepsilon_0}`, note: '전자기학' },
  { id: 65, title: '맥스웰 2', latex: String.raw`\nabla \cdot \mathbf{B}=0`, note: '간단한 벡터 방정식' },
  { id: 66, title: '맥스웰 3', latex: String.raw`\nabla \times \mathbf{E}=-\frac{\partial \mathbf{B}}{\partial t}`, note: '시간미분 포함' },
  { id: 67, title: '로렌츠 인자', latex: String.raw`\gamma=\frac{1}{\sqrt{1-v^2/c^2}}`, note: '상대론식' },
  { id: 68, title: '에너지 질량', latex: String.raw`E=mc^2`, note: '짧지만 상징적' },
  { id: 69, title: '블록 행렬', latex: String.raw`\begin{bmatrix} A & B \\ C & D \end{bmatrix}`, note: '문자 행렬' },
  { id: 70, title: '역행렬', latex: String.raw`A^{-1}=\frac{1}{\det A}\operatorname{adj}(A)`, note: '행렬식 포함' },
  { id: 71, title: '고유값', latex: String.raw`A\mathbf{x}=\lambda\mathbf{x}`, note: '선형대수 기본' },
  { id: 72, title: '대각화', latex: String.raw`A=PDP^{-1}`, note: '행렬 분해' },
  { id: 73, title: '정사영', latex: String.raw`\operatorname{proj}_u v = \frac{\langle v,u \rangle}{\langle u,u \rangle}u`, note: '내적 기반' },
  { id: 74, title: '헤시안', latex: String.raw`H_f(x)=\left[\frac{\partial^2 f}{\partial x_i \partial x_j}\right]`, note: '이阶미분 행렬' },
  { id: 75, title: '야코비안', latex: String.raw`J=\begin{vmatrix} \frac{\partial x}{\partial u} & \frac{\partial x}{\partial v} \\ \frac{\partial y}{\partial u} & \frac{\partial y}{\partial v} \end{vmatrix}`, note: '조금 어려움' },
  { id: 76, title: '최적화 1', latex: String.raw`\nabla f(x^*)=0`, note: '최적화 기본' },
  { id: 77, title: '최적화 2', latex: String.raw`x^{(k+1)}=x^{(k)}-\eta \nabla f(x^{(k)})`, note: '경사하강법' },
  { id: 78, title: '라그랑주 승수', latex: String.raw`\mathcal{L}(x,\lambda)=f(x)+\lambda g(x)`, note: '최적화 제약식' },
  { id: 79, title: '소프트맥스', latex: String.raw`\sigma(z_i)=\frac{e^{z_i}}{\sum_{j=1}^{K} e^{z_j}}`, note: 'ML 식' },
  { id: 80, title: '크로스엔트로피', latex: String.raw`L=-\sum_{i=1}^{K} y_i \log \hat{y}_i`, note: '머신러닝 자주 등장' },
  { id: 81, title: '가우시안 커널', latex: String.raw`k(x,x')=\exp\left(-\frac{\|x-x'\|^2}{2\sigma^2}\right)`, note: '지수와 노름' },
  { id: 82, title: '베이즈 정리', latex: String.raw`P(A\mid B)=\frac{P(B\mid A)P(A)}{P(B)}`, note: '조건부 방향 바뀜 주의' },
  { id: 83, title: '로지스틱 함수', latex: String.raw`\sigma(x)=\frac{1}{1+e^{-x}}`, note: '시그모이드' },
  { id: 84, title: '정보이론', latex: String.raw`H(X)=-\sum_{x} p(x)\log p(x)`, note: '엔트로피 정의' },
  { id: 85, title: 'KL divergence', latex: String.raw`D_{KL}(P\|Q)=\sum_x P(x)\log\frac{P(x)}{Q(x)}`, note: '정보량 식' },
  { id: 86, title: '미분기하', latex: String.raw`ds^2 = g_{ij} dx^i dx^j`, note: '상대적으로 어려움' },
  { id: 87, title: '크리스토펠', latex: String.raw`\Gamma^k_{ij}=\frac{1}{2}g^{k\ell}(\partial_i g_{j\ell}+\partial_j g_{i\ell}-\partial_\ell g_{ij})`, note: '난이도 상승' },
  { id: 88, title: '리만합', latex: String.raw`\sum_{i=1}^{n} f(x_i^*)\Delta x`, note: '적분 근사' },
  { id: 89, title: '편도함수 2', latex: String.raw`\frac{\partial^2 u}{\partial t^2}=c^2\frac{\partial^2 u}{\partial x^2}`, note: '파동방정식' },
  { id: 90, title: '열방정식', latex: String.raw`\frac{\partial u}{\partial t}=\alpha \frac{\partial^2 u}{\partial x^2}`, note: 'PDE 기본' },
  { id: 91, title: '나비에-스토크스 느낌', latex: String.raw`\rho\left(\frac{\partial \mathbf{u}}{\partial t}+\mathbf{u}\cdot\nabla\mathbf{u}\right)=-\nabla p+\mu \nabla^2\mathbf{u}`, note: '길고 복잡함' },
  { id: 92, title: '복소적분', latex: String.raw`\oint_{|z|=1} \frac{1}{z} \, dz = 2\pi i`, note: '복소해석' },
  { id: 93, title: '잔여정리', latex: String.raw`\oint_C f(z) \, dz = 2\pi i \sum \operatorname{Res}(f,a_k)`, note: '조금 상급' },
  { id: 94, title: '감마함수', latex: String.raw`\Gamma(s)=\int_{0}^{\infty} x^{s-1}e^{-x} \, dx`, note: '특수함수' },
  { id: 95, title: '제타함수', latex: String.raw`\zeta(s)=\sum_{n=1}^{\infty} \frac{1}{n^s}`, note: '수론 느낌' },
  { id: 96, title: '모듈러', latex: String.raw`a \equiv b \pmod n`, note: '정수론 기호' },
  { id: 97, title: '군론', latex: String.raw`G=\langle a,b \mid a^2=b^3=e \rangle`, note: '군 발표기' },
  { id: 98, title: '카테고리 화살표', latex: String.raw`A \xrightarrow{f} B \xrightarrow{g} C`, note: '화살표 표기' },
  { id: 99, title: '함수 합성', latex: String.raw`(g\circ f)(x)=g(f(x))`, note: '합성함수' },
  { id: 100, title: '고난도 종합', latex: String.raw`\sum_{n=1}^{\infty} \int_{0}^{1} \frac{x^n}{1+x^2} \, dx`, note: '합과 적분이 함께 있는 문제' },
]
