export type PracticeItem = {
  id: number
  category: string
  title: string
  latex: string
  note: string
}

function makeCategory(category: string, items: Omit<PracticeItem, 'category'>[]) {
  return items.map((item) => ({ ...item, category }))
}

const algebra = makeCategory('대수', [
  { id: 1, title: '기본 분수', latex: String.raw`\frac{a+b}{c+d}`, note: '분수 기본기' },
  { id: 2, title: '인수분해 꼴', latex: String.raw`\frac{x^2-1}{x+1}`, note: '인수분해가 떠오르는 꼴' },
  { id: 3, title: '연분수', latex: String.raw`1+\frac{1}{1+\frac{1}{x}}`, note: '중첩 분수' },
  { id: 4, title: '이항식 1', latex: String.raw`(x+y)^2=x^2+2xy+y^2`, note: '전개식' },
  { id: 5, title: '이항식 2', latex: String.raw`(a-b)^2=a^2-2ab+b^2`, note: '전개식' },
  { id: 6, title: '지수 규칙', latex: String.raw`x^m x^n=x^{m+n}`, note: '지수 법칙' },
  { id: 7, title: '지수 분수', latex: String.raw`x^{\frac{1}{2}}=\sqrt{x}`, note: '루트와 지수' },
  { id: 8, title: '로그 법칙 1', latex: String.raw`\log(ab)=\log a+\log b`, note: '곱의 로그' },
  { id: 9, title: '로그 법칙 2', latex: String.raw`\log\frac{a}{b}=\log a-\log b`, note: '나눗셈 로그' },
  { id: 10, title: '대수 방정식', latex: String.raw`x^2-5x+6=0`, note: '이차방정식' },
  { id: 11, title: '완전제곱', latex: String.raw`x^2+2xy+y^2=(x+y)^2`, note: '완전제곱식' },
  { id: 12, title: '절댓값 방정식', latex: String.raw`|x-3|=2`, note: '절댓값' },
  { id: 13, title: '유리식', latex: String.raw`\frac{x^2-4}{x-2}=x+2`, note: '약분 꼴' },
  { id: 14, title: '근호 제거', latex: String.raw`\sqrt{x+1}=x-1`, note: '근호 포함 방정식' },
  { id: 15, title: '다항식', latex: String.raw`p(x)=x^4-3x^2+2`, note: '다항식' },
  { id: 16, title: '합성식', latex: String.raw`f(g(x))=x^2+1`, note: '합성 함수' },
  { id: 17, title: '조합식 1', latex: String.raw`\binom{n}{r}=\frac{n!}{r!(n-r)!}`, note: '조합 공식' },
  { id: 18, title: '조합식 2', latex: String.raw`{}_nC_r=\frac{n!}{r!(n-r)!}`, note: '표기 변형' },
  { id: 19, title: '순열', latex: String.raw`{}_nP_r=\frac{n!}{(n-r)!}`, note: '순열 공식' },
  { id: 20, title: '계승', latex: String.raw`n!=1\cdot2\cdot\cdots\cdot n`, note: '팩토리얼' },
  { id: 21, title: '부분분수', latex: String.raw`\frac{1}{x(x+1)}=\frac{1}{x}-\frac{1}{x+1}`, note: '부분분수 분해' },
  { id: 22, title: '대칭식', latex: String.raw`x+y=y+x`, note: '교환법칙' },
  { id: 23, title: '결합법칙', latex: String.raw`(x+y)+z=x+(y+z)`, note: '결합법칙' },
  { id: 24, title: '분배법칙', latex: String.raw`a(b+c)=ab+ac`, note: '분배법칙' },
  { id: 25, title: '거듭제곱', latex: String.raw`(x^m)^n=x^{mn}`, note: '거듭제곱 법칙' },
  { id: 26, title: '삼각함수 덧셈', latex: String.raw`\sin(x+y)=\sin x\cos y+\cos x\sin y`, note: '덧셈정리' },
  { id: 27, title: '삼각함수 덧셈2', latex: String.raw`\cos(x+y)=\cos x\cos y-\sin x\sin y`, note: '덧셈정리' },
  { id: 28, title: '이차식', latex: String.raw`ax^2+bx+c`, note: '기본 이차식' },
  { id: 29, title: '유리화', latex: String.raw`\frac{1}{\sqrt{2}}=\frac{\sqrt{2}}{2}`, note: '유리화' },
  { id: 30, title: '대입', latex: String.raw`x=2\Rightarrow x^2=4`, note: '대입' },
  { id: 31, title: '연립 1', latex: String.raw`\begin{cases} x+y=3\\ x-y=1 \end{cases}`, note: '연립방정식' },
  { id: 32, title: '연립 2', latex: String.raw`\begin{cases} 2x+3y=7\\ x-y=1 \end{cases}`, note: '연립방정식' },
  { id: 33, title: '분수식', latex: String.raw`\frac{x}{y}+\frac{y}{x}`, note: '분수 합' },
  { id: 34, title: '항등식', latex: String.raw`(x-1)(x+1)=x^2-1`, note: '항등식' },
  { id: 35, title: '다중 첨자', latex: String.raw`a_{m,n}^{k}`, note: '다중 첨자' },
  { id: 36, title: '절댓값2', latex: String.raw`|x|+|y|`, note: '절댓값 합' },
  { id: 37, title: '루트합', latex: String.raw`\sqrt{x}+\sqrt{y}`, note: '루트 합' },
  { id: 38, title: '로그 밑변환', latex: String.raw`\log_a b=\frac{\ln b}{\ln a}`, note: '밑변환' },
  { id: 39, title: '복소대수', latex: String.raw`(a+bi)(c+di)`, note: '복소수 곱' },
  { id: 40, title: '대수 종합', latex: String.raw`\frac{x^2-1}{x-1}=x+1`, note: '종합' },
  { id: 41, title: '치환 1', latex: String.raw`u=x^2+1`, note: '변수 치환' },
  { id: 42, title: '치환 2', latex: String.raw`v=\sqrt{x+1}`, note: '변수 치환' },
  { id: 43, title: '항등 2', latex: String.raw`(x+y)^3=x^3+3x^2y+3xy^2+y^3`, note: '전개' },
  { id: 44, title: '인수분해2', latex: String.raw`x^3-y^3=(x-y)(x^2+xy+y^2)`, note: '인수분해' },
  { id: 45, title: '삼차식', latex: String.raw`x^3+ax^2+bx+c`, note: '삼차식' },
  { id: 46, title: '라디칼', latex: String.raw`\sqrt[4]{x^4+y^4}`, note: '4제곱근' },
  { id: 47, title: '분모통일', latex: String.raw`\frac{a}{b}+\frac{c}{d}=\frac{ad+bc}{bd}`, note: '분모 통일' },
  { id: 48, title: '차수', latex: String.raw`\deg p(x)=n`, note: '차수' },
  { id: 49, title: '나눗셈', latex: String.raw`x=yq+r`, note: '나눗셈 정리' },
  { id: 50, title: '대수 마무리', latex: String.raw`\frac{1}{1-x}=\sum_{n=0}^{\infty} x^n`, note: '급수 연결' },
])

const calculus = makeCategory('미적분', [
  { id: 101, title: '정적분 1', latex: String.raw`\int_{0}^{1} x^2 \, dx`, note: '기본 정적분' },
  { id: 102, title: '정적분 2', latex: String.raw`\int_{-\pi}^{\pi} \cos x \, dx`, note: '대칭 구간' },
  { id: 103, title: '부정적분', latex: String.raw`\int e^x \, dx=e^x+C`, note: '상수 포함' },
  { id: 104, title: '치환적분', latex: String.raw`\int f(g(x))g'(x) \, dx=\int f(u) \, du`, note: '치환' },
  { id: 105, title: '부분적분', latex: String.raw`\int u \, dv=uv-\int v \, du`, note: '부분적분' },
  { id: 106, title: '미분 1', latex: String.raw`\frac{d}{dx}x^n=nx^{n-1}`, note: '미분법' },
  { id: 107, title: '미분 2', latex: String.raw`\frac{d}{dx}\sin x=\cos x`, note: '삼각함수 미분' },
  { id: 108, title: '미분 3', latex: String.raw`\frac{d}{dx}\cos x=-\sin x`, note: '삼각함수 미분' },
  { id: 109, title: '미분 4', latex: String.raw`\frac{d}{dx}e^x=e^x`, note: '지수함수 미분' },
  { id: 110, title: '미분 5', latex: String.raw`\frac{d}{dx}\ln x=\frac{1}{x}`, note: '로그함수 미분' },
  { id: 111, title: '도함수', latex: String.raw`f'(x)=\lim_{h\to 0}\frac{f(x+h)-f(x)}{h}`, note: '정의' },
  { id: 112, title: '적분 1', latex: String.raw`\int_0^\infty e^{-x} \, dx=1`, note: '무한적분' },
  { id: 113, title: '적분 2', latex: String.raw`\int_0^\pi \sin x \, dx=2`, note: '기본 삼각적분' },
  { id: 114, title: '적분 3', latex: String.raw`\int_0^1 \frac{1}{1+x^2} \, dx=\frac{\pi}{4}`, note: '아크탄젠트' },
  { id: 115, title: '극한 1', latex: String.raw`\lim_{x\to 0}\frac{\sin x}{x}=1`, note: '대표 극한' },
  { id: 116, title: '극한 2', latex: String.raw`\lim_{x\to\infty}\frac{2x^2+1}{x^2-3}=2`, note: '유리함수 극한' },
  { id: 117, title: '극한 3', latex: String.raw`\lim_{n\to\infty}\left(1+\frac{1}{n}\right)^n=e`, note: 'e' },
  { id: 118, title: '합 1', latex: String.raw`\sum_{n=1}^{\infty} \frac{1}{n^2}=\frac{\pi^2}{6}`, note: '바젤 문제' },
  { id: 119, title: '합 2', latex: String.raw`\sum_{k=0}^{m} 2^k=2^{m+1}-1`, note: '등비급수' },
  { id: 120, title: '합 3', latex: String.raw`\sum_{i=1}^{n} i=\frac{n(n+1)}{2}`, note: '등차합' },
  { id: 121, title: '합 4', latex: String.raw`\sum_{i=1}^{n} i^2=\frac{n(n+1)(2n+1)}{6}`, note: '제곱합' },
  { id: 122, title: '합 5', latex: String.raw`\prod_{k=1}^{n} k=n!`, note: '곱' },
  { id: 123, title: '로그 적분', latex: String.raw`\int_0^1 \log x \, dx=-1`, note: '로그적분' },
  { id: 124, title: '도함수2', latex: String.raw`\frac{d}{dx}x^{-1}=-x^{-2}`, note: '음수 지수' },
  { id: 125, title: '도함수3', latex: String.raw`\frac{d}{dx}\tan x=\sec^2 x`, note: '탄젠트 미분' },
  { id: 126, title: '연쇄법칙', latex: String.raw`\frac{d}{dx}f(g(x))=f'(g(x))g'(x)`, note: '체인룰' },
  { id: 127, title: '평균값정리', latex: String.raw`f'(c)=\frac{f(b)-f(a)}{b-a}`, note: '평균값정리' },
  { id: 128, title: '테일러 1', latex: String.raw`e^x=\sum_{n=0}^{\infty} \frac{x^n}{n!}`, note: '테일러' },
  { id: 129, title: '테일러 2', latex: String.raw`\sin x=\sum_{n=0}^{\infty} \frac{(-1)^n x^{2n+1}}{(2n+1)!}`, note: '사인 급수' },
  { id: 130, title: '테일러 3', latex: String.raw`\cos x=\sum_{n=0}^{\infty} \frac{(-1)^n x^{2n}}{(2n)!}`, note: '코사인 급수' },
  { id: 131, title: '로피탈', latex: String.raw`\lim_{x\to 0}\frac{1-\cos x}{x^2}=\frac{1}{2}`, note: '극한' },
  { id: 132, title: '미분방정식 1', latex: String.raw`\frac{dy}{dx}=ky`, note: '성장모형' },
  { id: 133, title: '미분방정식 2', latex: String.raw`\frac{dy}{dx}+y=e^x`, note: '선형 ODE' },
  { id: 134, title: '미분방정식 3', latex: String.raw`\frac{\partial u}{\partial t}=\alpha \frac{\partial^2 u}{\partial x^2}`, note: '열방정식' },
  { id: 135, title: '미분방정식 4', latex: String.raw`\frac{\partial^2 u}{\partial t^2}=c^2\frac{\partial^2 u}{\partial x^2}`, note: '파동방정식' },
  { id: 136, title: '벡터미적분 1', latex: String.raw`\nabla \cdot \mathbf{F}=\frac{\partial F_x}{\partial x}+\frac{\partial F_y}{\partial y}`, note: '발산' },
  { id: 137, title: '벡터미적분 2', latex: String.raw`\nabla \times \mathbf{F}`, note: '회전' },
  { id: 138, title: '벡터미적분 3', latex: String.raw`\oint_C P \, dx+Q \, dy`, note: '선적분' },
  { id: 139, title: '정적분4', latex: String.raw`\int_{0}^{\pi} \sin^2 x \, dx=\frac{\pi}{2}`, note: '삼각적분' },
  { id: 140, title: '정적분5', latex: String.raw`\int_{-1}^{1} x^3 \, dx=0`, note: '홀함수' },
  { id: 141, title: '정적분6', latex: String.raw`\int_{0}^{1} x \, dx=\frac{1}{2}`, note: '기본 적분' },
  { id: 142, title: '정적분7', latex: String.raw`\int_{0}^{1} x^2 \, dx=\frac{1}{3}`, note: '기본 적분' },
  { id: 143, title: '정적분8', latex: String.raw`\int_{0}^{1} x^3 \, dx=\frac{1}{4}`, note: '기본 적분' },
  { id: 144, title: '정적분9', latex: String.raw`\int_{0}^{1} \sqrt{x} \, dx=\frac{2}{3}`, note: '루트 적분' },
  { id: 145, title: '정적분10', latex: String.raw`\int_{0}^{1} \frac{1}{1+x} \, dx=\ln 2`, note: '로그 적분' },
  { id: 146, title: '극한4', latex: String.raw`\lim_{x\to 0}\frac{e^x-1}{x}=1`, note: '지수 극한' },
  { id: 147, title: '극한5', latex: String.raw`\lim_{x\to 0}\frac{\ln(1+x)}{x}=1`, note: '로그 극한' },
  { id: 148, title: '극한6', latex: String.raw`\lim_{x\to 0}\frac{\tan x}{x}=1`, note: '탄젠트 극한' },
  { id: 149, title: '급수1', latex: String.raw`\sum_{n=0}^{\infty} ar^n=\frac{a}{1-r}`, note: '등비급수' },
  { id: 150, title: '적분 종합', latex: String.raw`\int_{0}^{1} \frac{x^n}{1+x^2} \, dx`, note: '종합' },
])

const linearAlgebra = makeCategory('선형대수', [
  { id: 201, title: '행렬 1', latex: String.raw`\begin{bmatrix} a & b \\ c & d \end{bmatrix}`, note: '2x2 행렬' },
  { id: 202, title: '행렬 2', latex: String.raw`\begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix}`, note: '단위행렬' },
  { id: 203, title: '벡터 1', latex: String.raw`\vec{v}=\begin{bmatrix} x \\ y \\ z \end{bmatrix}`, note: '벡터와 행렬' },
  { id: 204, title: '벡터 2', latex: String.raw`\|x\|_2=\sqrt{\sum_{i=1}^{n} x_i^2}`, note: '노름' },
  { id: 205, title: '내적', latex: String.raw`\langle u,v \rangle = \sum_{i=1}^{n} u_i v_i`, note: '내적' },
  { id: 206, title: '고유값', latex: String.raw`A\mathbf{x}=\lambda\mathbf{x}`, note: '고유값' },
  { id: 207, title: '대각화', latex: String.raw`A=PDP^{-1}`, note: '대각화' },
  { id: 208, title: '역행렬', latex: String.raw`A^{-1}A=I`, note: '역행렬' },
  { id: 209, title: '전치', latex: String.raw`A^T=(a_{ji})`, note: '전치행렬' },
  { id: 210, title: '행렬식 1', latex: String.raw`\det\begin{bmatrix} a & b \\ c & d \end{bmatrix}=ad-bc`, note: '행렬식' },
  { id: 211, title: '행렬식 2', latex: String.raw`\det(AB)=\det(A)\det(B)`, note: '곱셈 법칙' },
  { id: 212, title: '랭크', latex: String.raw`\operatorname{rank}(A)`, note: '랭크' },
  { id: 213, title: '정사영', latex: String.raw`\operatorname{proj}_u v`, note: '정사영' },
  { id: 214, title: 'Gram-Schmidt', latex: String.raw`u_i=v_i-\sum_{j=1}^{i-1} \operatorname{proj}_{u_j} v_i`, note: '정규직교화' },
  { id: 215, title: '기저', latex: String.raw`\{e_1,e_2,e_3\}`, note: '기저' },
  { id: 216, title: '선형결합', latex: String.raw`a_1v_1+a_2v_2+\cdots+a_nv_n`, note: '선형결합' },
  { id: 217, title: '선형독립', latex: String.raw`c_1v_1+\cdots+c_nv_n=0`, note: '독립성' },
  { id: 218, title: '기본공간', latex: String.raw`\operatorname{Null}(A)`, note: '영공간' },
  { id: 219, title: '열공간', latex: String.raw`\operatorname{Col}(A)`, note: '열공간' },
  { id: 220, title: '행공간', latex: String.raw`\operatorname{Row}(A)`, note: '행공간' },
  { id: 221, title: 'SVD', latex: String.raw`A=U\Sigma V^T`, note: '특이값분해' },
  { id: 222, title: '투영행렬', latex: String.raw`P=A(A^TA)^{-1}A^T`, note: '투영' },
  { id: 223, title: '직교행렬', latex: String.raw`Q^TQ=I`, note: '직교' },
  { id: 224, title: '대칭행렬', latex: String.raw`A=A^T`, note: '대칭' },
  { id: 225, title: '고유벡터', latex: String.raw`A\mathbf{v}=\lambda\mathbf{v}`, note: '고유벡터' },
  { id: 226, title: '이차형식', latex: String.raw`x^TAx`, note: '이차형식' },
  { id: 227, title: '랭크-널리티', latex: String.raw`\operatorname{rank}(A)+\operatorname{nullity}(A)=n`, note: '랭크-널리티' },
  { id: 228, title: '선형시스템', latex: String.raw`A\mathbf{x}=\mathbf{b}`, note: '선형시스템' },
  { id: 229, title: '가우스 소거', latex: String.raw`\begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}`, note: '소거법' },
  { id: 230, title: '블록행렬', latex: String.raw`\begin{bmatrix} A & B \\ C & D \end{bmatrix}`, note: '블록 행렬' },
  { id: 231, title: '선형변환 1', latex: String.raw`T(\mathbf{x})=A\mathbf{x}`, note: '선형변환' },
  { id: 232, title: '선형변환 2', latex: String.raw`T(\mathbf{u}+\mathbf{v})=T(\mathbf{u})+T(\mathbf{v})`, note: '가법성' },
  { id: 233, title: '선형변환 3', latex: String.raw`T(c\mathbf{x})=cT(\mathbf{x})`, note: '동차성' },
  { id: 234, title: '내적공간', latex: String.raw`\langle x,y \rangle = x^Ty`, note: '내적공간' },
  { id: 235, title: '코시슈바르츠', latex: String.raw`|x^Ty|\le \|x\|_2\|y\|_2`, note: '부등식' },
  { id: 236, title: '벡터합', latex: String.raw`\mathbf{u}+\mathbf{v}`, note: '벡터합' },
  { id: 237, title: '벡터차', latex: String.raw`\mathbf{u}-\mathbf{v}`, note: '벡터차' },
  { id: 238, title: '기저변환', latex: String.raw`[x]_B=P^{-1}x`, note: '기저변환' },
  { id: 239, title: '공간차원', latex: String.raw`\dim V=n`, note: '차원' },
  { id: 240, title: '복소벡터', latex: String.raw`\mathbf{z}\in\mathbb{C}^n`, note: '복소벡터' },
  { id: 241, title: '직교분해', latex: String.raw`x=\hat{x}+e`, note: '직교분해' },
  { id: 242, title: '정규직교', latex: String.raw`Q^TQ=I`, note: '정규직교' },
  { id: 243, title: '행렬곱', latex: String.raw`(AB)_{ij}=\sum_k a_{ik}b_{kj}`, note: '행렬곱' },
  { id: 244, title: '행렬곱2', latex: String.raw`AB\neq BA`, note: '비가환성' },
  { id: 245, title: '고유다항식', latex: String.raw`\det(A-\lambda I)=0`, note: '고유다항식' },
  { id: 246, title: '직접합', latex: String.raw`V\oplus W`, note: '직접합' },
  { id: 247, title: '공간합', latex: String.raw`U+W`, note: '부분공간 합' },
  { id: 248, title: '선형독립2', latex: String.raw`\alpha_1v_1+\cdots+\alpha_kv_k=0`, note: '독립성' },
  { id: 249, title: '랭크2', latex: String.raw`\operatorname{rank}(A)=r`, note: '랭크' },
  { id: 250, title: '선형대수 종합', latex: String.raw`A=Q\Lambda Q^T`, note: '대칭행렬 대각화' },
])

const electromagnetism = makeCategory('전자기학', [
  { id: 301, title: '가우스 법칙', latex: String.raw`\nabla \cdot \mathbf{E}=\frac{\rho}{\varepsilon_0}`, note: '전기장 발산' },
  { id: 302, title: '자기 가우스 법칙', latex: String.raw`\nabla \cdot \mathbf{B}=0`, note: '자기 단극자 없음' },
  { id: 303, title: '패러데이 법칙', latex: String.raw`\nabla \times \mathbf{E}=-\frac{\partial \mathbf{B}}{\partial t}`, note: '유도 전기장' },
  { id: 304, title: '암페어-맥스웰', latex: String.raw`\nabla \times \mathbf{B}=\mu_0\mathbf{J}+\mu_0\varepsilon_0\frac{\partial \mathbf{E}}{\partial t}`, note: '변위전류 포함' },
  { id: 305, title: '쿨롱 법칙', latex: String.raw`\mathbf{F}=\frac{1}{4\pi\varepsilon_0}\frac{q_1q_2}{r^2}\hat{\mathbf{r}}`, note: '쿨롱 힘' },
  { id: 306, title: '로렌츠 힘', latex: String.raw`\mathbf{F}=q(\mathbf{E}+\mathbf{v}\times\mathbf{B})`, note: '로렌츠 힘' },
  { id: 307, title: '전위 정의', latex: String.raw`\mathbf{E}=-\nabla V`, note: '스칼라 퍼텐셜' },
  { id: 308, title: '벡터퍼텐셜', latex: String.raw`\mathbf{B}=\nabla\times\mathbf{A}`, note: '벡터 퍼텐셜' },
  { id: 309, title: '포아송 방정식', latex: String.raw`\nabla^2 V=-\frac{\rho}{\varepsilon_0}`, note: '정전기' },
  { id: 310, title: '라플라스 방정식', latex: String.raw`\nabla^2 V=0`, note: '무전하 영역' },
  { id: 311, title: '전기력선속', latex: String.raw`\oint_S \mathbf{E}\cdot d\mathbf{A}=\frac{Q_{\mathrm{enc}}}{\varepsilon_0}`, note: '적분형 가우스 법칙' },
  { id: 312, title: '자기력선속', latex: String.raw`\oint_S \mathbf{B}\cdot d\mathbf{A}=0`, note: '적분형' },
  { id: 313, title: '패러데이 적분형', latex: String.raw`\oint_C \mathbf{E}\cdot d\mathbf{l}=-\frac{d\Phi_B}{dt}`, note: '전자기 유도' },
  { id: 314, title: '암페어 적분형', latex: String.raw`\oint_C \mathbf{B}\cdot d\mathbf{l}=\mu_0 I_{\mathrm{enc}}+\mu_0\varepsilon_0\frac{d\Phi_E}{dt}`, note: '순환 적분' },
  { id: 315, title: '파동방정식 E', latex: String.raw`\nabla^2 \mathbf{E}-\mu_0\varepsilon_0\frac{\partial^2 \mathbf{E}}{\partial t^2}=0`, note: '전자기파' },
  { id: 316, title: '파동방정식 B', latex: String.raw`\nabla^2 \mathbf{B}-\mu_0\varepsilon_0\frac{\partial^2 \mathbf{B}}{\partial t^2}=0`, note: '전자기파' },
  { id: 317, title: '파동속도', latex: String.raw`c=\frac{1}{\sqrt{\mu_0\varepsilon_0}}`, note: '광속' },
  { id: 318, title: '포인팅 벡터', latex: String.raw`\mathbf{S}=\frac{1}{\mu_0}\mathbf{E}\times\mathbf{B}`, note: '에너지 흐름' },
  { id: 319, title: '에너지 밀도', latex: String.raw`u=\frac{1}{2}\varepsilon_0 E^2+\frac{1}{2\mu_0}B^2`, note: '장 에너지' },
  { id: 320, title: '비오-사바르', latex: String.raw`d\mathbf{B}=\frac{\mu_0}{4\pi}\frac{I d\mathbf{l}\times\hat{\mathbf{r}}}{r^2}`, note: '전류 자기장' },
  { id: 321, title: '직선도선 자기장', latex: String.raw`B=\frac{\mu_0 I}{2\pi r}`, note: '직선도선' },
  { id: 322, title: '원형코일 중심', latex: String.raw`B=\frac{\mu_0 I}{2R}`, note: '원형 루프' },
  { id: 323, title: '솔레노이드', latex: String.raw`B=\mu_0 n I`, note: '이상 솔레노이드' },
  { id: 324, title: '축전기 에너지', latex: String.raw`U=\frac{1}{2}CV^2`, note: '축전기' },
  { id: 325, title: '축전기 전하', latex: String.raw`Q=CV`, note: '축전기 기본' },
  { id: 326, title: '평행판 전기장', latex: String.raw`E=\frac{\sigma}{\varepsilon_0}`, note: '평행판' },
  { id: 327, title: '전위차', latex: String.raw`\Delta V=-\int_a^b \mathbf{E}\cdot d\mathbf{l}`, note: '전위차' },
  { id: 328, title: '전류밀도', latex: String.raw`\mathbf{J}=\sigma\mathbf{E}`, note: '옴 법칙 미분형' },
  { id: 329, title: '저항', latex: String.raw`R=\rho\frac{L}{A}`, note: '재료 저항' },
  { id: 330, title: '전력', latex: String.raw`P=IV`, note: '전력' },
  { id: 331, title: '전력2', latex: String.raw`P=I^2R`, note: '저항손실' },
  { id: 332, title: '자속', latex: String.raw`\Phi_B=\int_S \mathbf{B}\cdot d\mathbf{A}`, note: '자기 선속' },
  { id: 333, title: '전속', latex: String.raw`\Phi_E=\int_S \mathbf{E}\cdot d\mathbf{A}`, note: '전기 선속' },
  { id: 334, title: '유도기전력', latex: String.raw`\mathcal{E}=-\frac{d\Phi_B}{dt}`, note: '패러데이' },
  { id: 335, title: '인덕터', latex: String.raw`V=L\frac{dI}{dt}`, note: '인덕턴스' },
  { id: 336, title: '인덕터 에너지', latex: String.raw`U=\frac{1}{2}LI^2`, note: '자기 에너지' },
  { id: 337, title: 'RC 회로', latex: String.raw`q(t)=CV\left(1-e^{-t/RC}\right)`, note: '충전' },
  { id: 338, title: 'RL 회로', latex: String.raw`I(t)=\frac{V}{R}\left(1-e^{-Rt/L}\right)`, note: '전류 증가' },
  { id: 339, title: 'LC 진동', latex: String.raw`\omega=\frac{1}{\sqrt{LC}}`, note: '자유진동' },
  { id: 340, title: 'RLC 감쇠', latex: String.raw`L\frac{d^2q}{dt^2}+R\frac{dq}{dt}+\frac{q}{C}=0`, note: 'RLC 회로' },
  { id: 341, title: '경계조건 E', latex: String.raw`\hat{\mathbf{n}}\cdot(\mathbf{E}_2-\mathbf{E}_1)=\frac{\sigma_f}{\varepsilon_0}`, note: '법선 성분' },
  { id: 342, title: '경계조건 B', latex: String.raw`\hat{\mathbf{n}}\cdot(\mathbf{B}_2-\mathbf{B}_1)=0`, note: '자기장 법선' },
  { id: 343, title: '경계조건 H', latex: String.raw`\hat{\mathbf{n}}\times(\mathbf{H}_2-\mathbf{H}_1)=\mathbf{K}_f`, note: '접선 성분' },
  { id: 344, title: '유전변위', latex: String.raw`\mathbf{D}=\varepsilon \mathbf{E}`, note: '매질 응답' },
  { id: 345, title: '자기장세기', latex: String.raw`\mathbf{B}=\mu \mathbf{H}`, note: '매질 응답' },
  { id: 346, title: '분극', latex: String.raw`\mathbf{P}=\varepsilon_0\chi_e\mathbf{E}`, note: '분극' },
  { id: 347, title: '자화', latex: String.raw`\mathbf{M}=\chi_m\mathbf{H}`, note: '자화' },
  { id: 348, title: '편파', latex: String.raw`\mathbf{E}(z,t)=E_0\cos(kz-\omega t)\hat{\mathbf{x}}`, note: '평면파' },
  { id: 349, title: '복소 표현', latex: String.raw`\tilde{E}(z,t)=E_0 e^{i(kz-\omega t)}`, note: '복소수 파동' },
  { id: 350, title: '전자기학 종합', latex: String.raw`\nabla\times(\nabla\times\mathbf{E})=-\mu_0\frac{\partial \mathbf{J}}{\partial t}-\mu_0\varepsilon_0\frac{\partial^2 \mathbf{E}}{\partial t^2}`, note: '맥스웰 종합' },
])

export const practiceSet = [...algebra, ...calculus, ...linearAlgebra, ...electromagnetism]
export const practiceCategories = ['전체', '대수', '미적분', '선형대수', '전자기학'] as const
export type PracticeCategory = (typeof practiceCategories)[number]
